# GENERATED by build_envs.py - do not edit.
# One provider per distinct spoke account (default_tags satisfies the
# require_mandatory_tags SCP; per-row Tags override per-key on resources).

provider "huaweicloud" {
  alias      = "spoke_EXAMPLE_Prod_A"
  region     = var.home_region
  access_key = var.master_access_key
  secret_key = var.master_secret_key

  assume_role {
    agency_name = local.foundation.cross_account_agency_name
    domain_name = "EXAMPLE-Prod-A"
  }
  # Required by the organization tag guardrails; per-resource tags override.
  default_tags = var.default_tags
}

provider "huaweicloud" {
  alias      = "spoke_EXAMPLE_Sandbox1"
  region     = var.home_region
  access_key = var.master_access_key
  secret_key = var.master_secret_key

  assume_role {
    agency_name = local.foundation.cross_account_agency_name
    domain_name = "EXAMPLE-Sandbox1"
  }
  # Required by the organization tag guardrails; per-resource tags override.
  default_tags = var.default_tags
}
