# GENERATED by build_envs.py - do not edit.
# One spoke module call per SpokeVPCs row. The hub (module.network_hub) +
# local.vpc_flow_lts are defined in main.tf.

module "spoke_example_prod_a_vpc" {
  source    = "../../modules/network"
  providers = {
    huaweicloud       = huaweicloud.spoke_EXAMPLE_Prod_A
    huaweicloud.owner = huaweicloud.hub
  }

  environment  = var.environment
  enable_spoke = true
  spoke_vpc_name           = var.spokes["example-prod-a-vpc"].vpc_name
  spoke_vpc_cidr           = var.spokes["example-prod-a-vpc"].vpc_cidr
  spoke_vpc_tags           = var.spokes["example-prod-a-vpc"].vpc_tags
  spoke_subnets            = var.spokes["example-prod-a-vpc"].subnets
  spoke_er_attachment_name = var.spokes["example-prod-a-vpc"].er_attachment_name
  spoke_er_attach_subnet   = var.spokes["example-prod-a-vpc"].er_attach_subnet
  spoke_auto_add_route     = var.spokes["example-prod-a-vpc"].auto_add_route
  spoke_er_attach_enabled  = var.spokes["example-prod-a-vpc"].er_attach

  spoke_er_id                 = module.network_hub.er_id
  hub_route_table_ids         = module.network_hub.route_table_ids
  inbound_route_table         = var.inbound_route_table
  outbound_route_table        = var.outbound_route_table
  subnet_dns                  = var.subnet_dns
  enable_vpc_flow_logs        = var.enable_vpc_flow_logs
  flow_log_retention_days     = var.flow_log_retention_days

  depends_on = [module.network_hub]
}

module "spoke_example_sbx_vpc" {
  source    = "../../modules/network"
  providers = {
    huaweicloud       = huaweicloud.spoke_EXAMPLE_Sandbox1
    huaweicloud.owner = huaweicloud.hub
  }

  environment  = var.environment
  enable_spoke = true
  spoke_vpc_name           = var.spokes["example-sbx-vpc"].vpc_name
  spoke_vpc_cidr           = var.spokes["example-sbx-vpc"].vpc_cidr
  spoke_vpc_tags           = var.spokes["example-sbx-vpc"].vpc_tags
  spoke_subnets            = var.spokes["example-sbx-vpc"].subnets
  spoke_er_attachment_name = var.spokes["example-sbx-vpc"].er_attachment_name
  spoke_er_attach_subnet   = var.spokes["example-sbx-vpc"].er_attach_subnet
  spoke_auto_add_route     = var.spokes["example-sbx-vpc"].auto_add_route
  spoke_er_attach_enabled  = var.spokes["example-sbx-vpc"].er_attach

  spoke_er_id                 = module.network_hub.er_id
  hub_route_table_ids         = module.network_hub.route_table_ids
  inbound_route_table         = var.inbound_route_table
  outbound_route_table        = var.outbound_route_table
  subnet_dns                  = var.subnet_dns
  enable_vpc_flow_logs        = var.enable_vpc_flow_logs
  flow_log_retention_days     = var.flow_log_retention_days

  depends_on = [module.network_hub]
}
