provider "huaweicloud" {
  region     = var.home_region
  access_key = var.master_access_key
  secret_key = var.master_secret_key

  default_tags = var.default_tags
}

# Per-account assume_role providers (one per account named in the 11_SGACL
# SecurityGroups rows) are generated by build_envs.py into providers.generated.tf.
