# GENERATED by build_envs.py - do not edit.
# Org LTS log aggregation: member source lookups + converge/archive in the LTS admin.

data "huaweicloud_lts_streams" "lc_s0" {
  provider       = huaweicloud.acct_EXAMPLE_SharedInfra
  log_group_name = "example-hub-core-vpc-flowlog"
  name           = "example-hub-core-vpc-flowlog"
}

data "huaweicloud_lts_streams" "lc_s1" {
  provider       = huaweicloud.acct_EXAMPLE_SharedInfra
  log_group_name = "example-hub-edge-vpc-flowlog"
  name           = "example-hub-edge-vpc-flowlog"
}

data "huaweicloud_lts_streams" "lc_s2" {
  provider       = huaweicloud.acct_EXAMPLE_Prod_A
  log_group_name = "example-prod-a-vpc-flowlog"
  name           = "example-prod-a-vpc-flowlog"
}

data "huaweicloud_lts_streams" "lc_s3" {
  provider       = huaweicloud.acct_EXAMPLE_Sandbox1
  log_group_name = "example-sbx-vpc-flowlog"
  name           = "example-sbx-vpc-flowlog"
}

data "huaweicloud_lts_groups" "lc_acct_EXAMPLE_SharedInfra" {
  provider = huaweicloud.acct_EXAMPLE_SharedInfra
}

data "huaweicloud_lts_groups" "lc_acct_EXAMPLE_Prod_A" {
  provider = huaweicloud.acct_EXAMPLE_Prod_A
}

data "huaweicloud_lts_groups" "lc_acct_EXAMPLE_Sandbox1" {
  provider = huaweicloud.acct_EXAMPLE_Sandbox1
}

module "log_aggregation" {
  source    = "../../modules/log-aggregation"
  providers = { huaweicloud = huaweicloud.lts_admin }

  enable_log_aggregation       = var.enable_log_aggregation
  account_name                 = "EXAMPLE-LogArchive"
  home_region                  = var.home_region
  organization_id              = local.foundation.organization_id
  management_account_id        = local.foundation.accounts["EXAMPLE-LogArchive"].id
  archive_bucket_name          = var.archive_bucket_name
  kms_archive_alias            = var.kms_archive_alias
  archive_retention_days       = var.archive_retention_days
  archive_cold_after_days      = var.archive_cold_after_days
  converged_retention_days     = var.converged_retention_days
  transfer_period              = var.transfer_period
  transfer_period_unit         = var.transfer_period_unit
  archive_bucket_force_destroy = var.archive_bucket_force_destroy

  converge_members = {
    "EXAMPLE-SharedInfra" = {
      account_id = local.foundation.accounts["EXAMPLE-SharedInfra"].id
      mappings = [
        {
          source_log_group_id   = [for g in data.huaweicloud_lts_groups.lc_acct_EXAMPLE_SharedInfra.groups : g.id if g.name == "example-hub-core-vpc-flowlog"][0]
          target_log_group_name = "agg-example-sharedinfra-example-hub-core-vpc-flowlog"
          streams = [
            {
              source_log_stream_id   = data.huaweicloud_lts_streams.lc_s0.streams[0].id
              target_log_stream_name = "example-hub-core-vpc-flowlog"
            },
          ]
        },
        {
          source_log_group_id   = [for g in data.huaweicloud_lts_groups.lc_acct_EXAMPLE_SharedInfra.groups : g.id if g.name == "example-hub-edge-vpc-flowlog"][0]
          target_log_group_name = "agg-example-sharedinfra-example-hub-edge-vpc-flowlog"
          streams = [
            {
              source_log_stream_id   = data.huaweicloud_lts_streams.lc_s1.streams[0].id
              target_log_stream_name = "example-hub-edge-vpc-flowlog"
            },
          ]
        },
      ]
    }
    "EXAMPLE-Prod-A" = {
      account_id = local.foundation.accounts["EXAMPLE-Prod-A"].id
      mappings = [
        {
          source_log_group_id   = [for g in data.huaweicloud_lts_groups.lc_acct_EXAMPLE_Prod_A.groups : g.id if g.name == "example-prod-a-vpc-flowlog"][0]
          target_log_group_name = "agg-example-prod-a-example-prod-a-vpc-flowlog"
          streams = [
            {
              source_log_stream_id   = data.huaweicloud_lts_streams.lc_s2.streams[0].id
              target_log_stream_name = "example-prod-a-vpc-flowlog"
            },
          ]
        },
      ]
    }
    "EXAMPLE-Sandbox1" = {
      account_id = local.foundation.accounts["EXAMPLE-Sandbox1"].id
      mappings = [
        {
          source_log_group_id   = [for g in data.huaweicloud_lts_groups.lc_acct_EXAMPLE_Sandbox1.groups : g.id if g.name == "example-sbx-vpc-flowlog"][0]
          target_log_group_name = "agg-example-sandbox1-example-sbx-vpc-flowlog"
          streams = [
            {
              source_log_stream_id   = data.huaweicloud_lts_streams.lc_s3.streams[0].id
              target_log_stream_name = "example-sbx-vpc-flowlog"
            },
          ]
        },
      ]
    }
  }
}
