# GENERATED by build_envs.py - do not edit.
# Central audit + per-account ops monitoring.

# Central audit: org CTS tracker + audit/archive buckets + KMS + CTS LTS, in EXAMPLE-Security.
module "audit" {
  source    = "../../modules/compliance-audit"
  providers = { huaweicloud = huaweicloud.audit_admin }

  environment                = var.environment
  home_region                = var.home_region
  account_name               = "EXAMPLE-Security"
  audit_bucket_name          = var.audit_bucket_name
  kms_audit_alias            = var.kms_audit_alias
  cts_log_group_name         = var.cts_log_group_name
  cts_log_stream_name        = var.cts_log_stream_name
  member_account_ids         = local.member_account_ids
  audit_retention_days       = var.audit_retention_days
  audit_cold_after_days      = var.audit_cold_after_days
  lts_hot_retention_days     = var.lts_hot_retention_days
  kms_pending_days           = var.kms_pending_days
  audit_bucket_force_destroy = var.audit_bucket_force_destroy
}

module "ops_acct_EXAMPLE_Security" {
  source    = "../../modules/ops-monitoring"
  providers = { huaweicloud = huaweicloud.acct_EXAMPLE_Security }

  environment           = var.environment
  account_name          = "EXAMPLE-Security"
  topic_name            = var.topic_name
  subscribers           = var.subscribers
  one_click_alarms      = var.one_click_alarms
}

module "ops_acct_EXAMPLE_Prod_A" {
  source    = "../../modules/ops-monitoring"
  providers = { huaweicloud = huaweicloud.acct_EXAMPLE_Prod_A }

  environment           = var.environment
  account_name          = "EXAMPLE-Prod-A"
  topic_name            = var.topic_name
  subscribers           = var.subscribers
  one_click_alarms      = var.one_click_alarms
}

# CTS tracker (NO OBS/LTS transfer) in EXAMPLE-Sandbox1 - audit on, no storage charges.
module "cts_tracker_acct_EXAMPLE_Sandbox1" {
  source    = "../../modules/cts-tracker"
  providers = { huaweicloud = huaweicloud.acct_EXAMPLE_Sandbox1 }

  environment = var.environment
}
