# GENERATED by build_envs.py - do not edit.
# Application-scoped permission sets: each row's CustomPolicy from the workbook
# is attached verbatim as the permission set's custom identity policy.

resource "huaweicloud_identitycenter_permission_set" "app_admin" {
  instance_id      = local.foundation.identity_center_instance_id
  name             = "App-Admin"
  description      = "Full management scoped to the workload enterprise projects"
  session_duration = "PT8H"
}

resource "huaweicloud_identitycenter_permission_set" "sandbox_admin" {
  instance_id      = local.foundation.identity_center_instance_id
  name             = "Sandbox-Admin"
  description      = "Full management scoped to the sandbox enterprise projects"
  session_duration = "PT4H"
}
