"""Enforce the artifact comment convention.

Terraform we hand over is read by someone who has no access to the workbook,
the generator, the issue history or us. Comments therefore describe what the
configuration does and what will bite the reader - nothing else.

THE CONVENTION

  # --- Section title ---      every file opens with one; also marks groups
  # Note: One sentence.        a fact or an instruction, sentence case, full stop
  # Short label                a terse phrase directly above what it describes
  # Values: a, b               the accepted values of the attribute below
  # Account: NAME              per-block label in a generated fan-out

Nothing else. No paragraphs of rationale, no design essays, no wrapped
multi-sentence blocks.

BANNED - these belong in git history, the tracker or the guide, never here:

  change history      "removed", "previously", "no longer", "formerly"
  roadmap             TODO/FIXME, "deferred until", "parked", "not implemented"
  provenance          "GENERATED by build_envs", sheet names like 05_Network
  dead references     docs/*.md, cookbooks, files that do not ship
  dates               2026-09-01 and friends

A comment audit on 2026-09-29 found two further classes that a banned-word
check cannot see, so they are checked structurally: headings that label
nothing, and examples assigning variables that do not exist.

Run:  py -m lz_pipeline.comment_lint <dir> [<dir> ...]
"""

import re
import sys
from pathlib import Path

# High-precision markers. Each one was found in a real handover artifact.
BANNED = [
    (re.compile(r"\b(TODO|FIXME|XXX|HACK)\b"), "roadmap marker"),
    (re.compile(r"\bno longer\b|\bpreviously\b|\bused to be\b|\bformerly\b"
                r"|\bsuperseded\b|\bdeprecated\b"), "change history"),
    (re.compile(r"\(Removed\b|\bwas generated\b|\bun-merged\b|\bre-run build_envs\b"),
     "change history"),
    (re.compile(r"\bPARKED\b|\bon hold\b|\bnot implemented\b|\brevisit\b"), "parked work"),
    (re.compile(r"deferred (until|pending|-)|\bDeferred\b\s*\(|\bDay-1\b"), "deferred work"),
    (re.compile(r"GENERATED by|build_envs|lz_spec|engineering-notes|\bcodegen\b"),
     "internal tooling"),
    (re.compile(r"\b\d{2}_[A-Z][A-Za-z]+\b"), "workbook sheet name"),
    # A spec table reference, e.g. AuditSettings.cts_no_transfer_accounts. The
    # internal capital is what distinguishes it from ordinary prose.
    (re.compile(r"\b[A-Z][a-zA-Z]*[a-z][A-Z][a-zA-Z]*\.[a-z][a-z0-9_]{3,}\b"),
     "spec table reference"),
    # Module and env numbering that no longer exists in the shipped tree:
    # "module 06-compliance-audit", "env-05 observability", "modules-v2/x".
    (re.compile(r"\bmodules?[ -]\d{2}-|\benv-\d{2}\b|\bmodules?-v\d\b"
                r"|\bmodule \d+\b"), "stale module or env numbering"),
    (re.compile(r"[\w/-]+\.md\b"), "reference to a document that does not ship"),
    (re.compile(r"\b20\d{2}-\d{2}(-\d{2})?\b"), "date"),
    (re.compile(r"\bscaffolding\b|\bplaceholder only\b"), "scaffolding note"),
]

HEADING = re.compile(r"^# --- .+ ---$")
COMMENTED_ASSIGN = re.compile(r"^#\s*([a-z_][a-z0-9_]*\s*=|[{\[])")
VARIABLE = re.compile(r'^variable\s+"([^"]+)"', re.M)
ASSIGNMENT = re.compile(r"^(#\s*)?([a-z_][a-z0-9_]*)\s*=")

SKIP_DIRS = {".terraform", "__pycache__", "lzctl-logs", "state-backups"}


def comments(path):
    """Yield (lineno, text) for every comment line, ignoring '#' inside strings."""
    for i, line in enumerate(path.read_text(encoding="utf-8").split("\n"), 1):
        s, q, esc = [], False, False
        for ch in line:
            if esc:
                s.append(ch); esc = False; continue
            if ch == chr(92):
                s.append(ch); esc = True; continue
            if ch == '"':
                q = not q
            if ch == "#" and not q:
                yield i, line[len("".join(s)):].strip()
                break
            s.append(ch)


def _labels_something(lines, start, end, example):
    for l in lines[start + 1:end]:
        s = l.strip()
        if not s:
            continue
        if not s.startswith("#") or s.startswith("# Note:"):
            return True
        if example and COMMENTED_ASSIGN.match(s):
            return True
    return False


def check_headings(path):
    """A heading must be followed by content or a Note before the next heading."""
    example = path.suffix == ".example"
    lines = path.read_text(encoding="utf-8").split("\n")
    idx = [i for i, l in enumerate(lines) if HEADING.match(l.strip())]
    out = []
    for k, i in enumerate(idx):
        nxt = idx[k + 1] if k + 1 < len(idx) else len(lines)
        if not _labels_something(lines, i, nxt, example):
            out.append((i + 1, f"heading labels nothing: {lines[i].strip()}"))
    return out


def check_example_inputs(env_dir):
    """Every top-level name an example assigns must be a declared variable."""
    ex, var = env_dir / "terraform.tfvars.example", env_dir / "variables.tf"
    if not (ex.exists() and var.exists()):
        return []
    declared = set(VARIABLE.findall(var.read_text(encoding="utf-8")))
    out = []
    for n, line in enumerate(ex.read_text(encoding="utf-8").split("\n"), 1):
        if line.startswith((" ", "#   ")):            # nested inside an object
            continue
        s = line.strip()
        m = ASSIGNMENT.match(s)
        if m and not s.startswith("# ---") and m.group(2) not in declared:
            out.append((n, f"example assigns undeclared input: {m.group(2)}"))
    return out


def check(path):
    out = []
    text = path.read_text(encoding="utf-8").lstrip()
    if path.suffix == ".tf" and not text.startswith("# ---"):
        out.append((1, "file does not open with a '# --- Section ---' header"))
    out += check_headings(path)
    for lineno, c in comments(path):
        for rx, why in BANNED:
            if rx.search(c):
                out.append((lineno, f"{why}: {c[:72]}"))
                break
    return out


def run(roots):
    findings, checked = [], 0
    for root in roots:
        rp = Path(root)
        for p in sorted(rp.rglob("*")):
            if any(d in p.parts for d in SKIP_DIRS):
                continue
            if p.is_dir():
                for lineno, msg in check_example_inputs(p):
                    findings.append(
                        f"{(p / 'terraform.tfvars.example').as_posix()}:{lineno}: {msg}")
                continue
            if p.suffix not in (".tf", ".example"):
                continue
            checked += 1
            for lineno, msg in check(p):
                findings.append(f"{p.as_posix()}:{lineno}: {msg}")
    print(f"comment lint: {checked} file(s)")
    for f in findings:
        print("  " + f)
    print("  clean" if not findings else f"  {len(findings)} finding(s)")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(run(sys.argv[1:] or ["."]))
