"""Enforce the artifact comment convention.

Terraform we hand over is read by someone who has no access to the workbook,
the generator, the issue history or us. Comments therefore describe what the
configuration does and what will bite the reader - nothing else.

THE CONVENTION

  # --- Section title ---      every file opens with one; also marks groups
  # Note: One sentence.        a fact or an instruction, sentence case, full stop
  # Short label                a terse phrase directly above what it describes
  # Values: a, b               the accepted values of the attribute below
  # Account: NAME              per-block label in a generated fan-out

Nothing else. No paragraphs of rationale, no design essays, no wrapped
multi-sentence blocks.

BANNED - these belong in git history, the tracker or the guide, never here:

  change history      "removed", "previously", "no longer", "formerly"
  roadmap             TODO/FIXME, "deferred until", "parked", "not implemented"
  provenance          "GENERATED by build_envs", sheet names like 05_Network
  dead references     docs/*.md, cookbooks, files that do not ship
  dates               2026-09-01 and friends

Run:  py -m lz_pipeline.comment_lint <dir> [<dir> ...]
"""

import re
import sys
from pathlib import Path

# High-precision markers. Each one was found in a real handover artifact.
BANNED = [
    (re.compile(r"\b(TODO|FIXME|XXX|HACK)\b"), "roadmap marker"),
    (re.compile(r"\bno longer\b|\bpreviously\b|\bused to be\b|\bformerly\b"
                r"|\bsuperseded\b|\bdeprecated\b"), "change history"),
    (re.compile(r"\(Removed\b|\bwas generated\b|\bun-merged\b|\bre-run build_envs\b"),
     "change history"),
    (re.compile(r"\bPARKED\b|\bon hold\b|\bnot implemented\b|\brevisit\b"), "parked work"),
    (re.compile(r"deferred (until|pending|-)|\bDeferred\b\s*\(|\bDay-1\b"), "deferred work"),
    (re.compile(r"GENERATED by|build_envs|lz_spec|engineering-notes"), "internal tooling"),
    (re.compile(r"\b\d{2}_[A-Z][A-Za-z]+\b"), "workbook sheet name"),
    (re.compile(r"[\w/-]+\.md\b"), "reference to a document that does not ship"),
    (re.compile(r"\b20\d{2}-\d{2}(-\d{2})?\b"), "date"),
    (re.compile(r"\bscaffolding\b|\bplaceholder only\b"), "scaffolding note"),
]

HEADER = re.compile(r"^# --- .+ ---$")
NOTE = re.compile(r"^# Note: [A-Z].*[.?]$")
LABELLED = re.compile(r"^# (Values|Account|VPC|Env|Spoke): ")

SKIP_DIRS = {".terraform", "__pycache__", "lzctl-logs", "state-backups"}


def comments(path: Path):
    """Yield (lineno, text) for every comment line, ignoring '#' inside strings."""
    for i, line in enumerate(path.read_text(encoding="utf-8").split("\n"), 1):
        s, q, esc = [], False, False
        for ch in line:
            if esc:
                s.append(ch); esc = False; continue
            if ch == chr(92):
                s.append(ch); esc = True; continue
            if ch == '"':
                q = not q
            if ch == "#" and not q:
                yield i, line[len("".join(s)):].strip()
                break
            s.append(ch)


def check(path: Path):
    out = []
    text = path.read_text(encoding="utf-8").lstrip()
    if path.suffix == ".tf" and not text.startswith("# ---"):
        out.append((1, "file does not open with a '# --- Section ---' header"))
    for lineno, c in comments(path):
        for rx, why in BANNED:
            if rx.search(c):
                out.append((lineno, f"{why}: {c[:72]}"))
                break
    return out


def run(roots):
    findings, checked = [], 0
    for root in roots:
        for p in sorted(Path(root).rglob("*")):
            if p.suffix not in (".tf", ".example") or any(d in p.parts for d in SKIP_DIRS):
                continue
            checked += 1
            for lineno, msg in check(p):
                findings.append(f"{p.as_posix()}:{lineno}: {msg}")
    print(f"comment lint: {checked} file(s)")
    for f in findings:
        print("  " + f)
    print("  clean" if not findings else f"  {len(findings)} finding(s)")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(run(sys.argv[1:] or ["."]))
