"""Environment dependency graph (deps.json).

Scans each env's *.tf files for terraform_remote_state references and records
which earlier envs each env consumes. The graph is DERIVED from the code -
never hand-edited - and gives runners/docs a machine-readable apply order.

Rule LZR-008: a consumed env must sort strictly BEFORE its consumer (numeric
directory prefix). An inversion is exactly the class of bug behind the old
06/07 double-apply and fails the check.

Usage:
    py -m lz_pipeline deps --envs-dir <envs>
"""

import re
from pathlib import Path

# A consumed state key, wherever it appears: as a literal in a
# terraform_remote_state config, as a variables.tf default, or as a tfvars
# value (the envs wire keys through variables, e.g.
#   variable "network_state_key" { default = "envs/05-network/terraform.tfstate" }).
_STATE_KEY_RE = re.compile(r'envs/([0-9]{2}-[a-z0-9-]+)/terraform\.tfstate')
# local-backend remote state: path = "../00-bootstrap/terraform.tfstate"
_LOCAL_PATH_RE = re.compile(r'"\.\./([0-9]{2}-[a-z0-9-]+)/terraform\.tfstate"')


def _split_backend(text: str) -> tuple:
    """(text without its `backend "s3" { ... }` blocks, keys found inside them).

    The backend block holds the env's OWN state key, never a consumed one; it
    lives inline in providers.tf, so it is cut out by brace matching rather
    than by excluding a file.
    """
    own, out, pos = [], [], 0
    for m in re.finditer(r'backend\s+"s3"\s*\{', text):
        if m.start() < pos:
            continue
        depth, i = 1, m.end()
        while i < len(text) and depth:
            depth += {"{": 1, "}": -1}.get(text[i], 0)
            i += 1
        own += _STATE_KEY_RE.findall(text[m.start():i])
        out.append(text[pos:m.start()])
        pos = i
    out.append(text[pos:])
    return "".join(out), own


def scan(envs_dir: Path) -> dict:
    """{env_name: {"consumes": [env, ...]}} for every env dir, in order."""
    blobs, key_env = {}, {}
    for env in sorted(p for p in envs_dir.iterdir() if p.is_dir()):
        if not re.match(r"^[0-9]{2}-", env.name):
            continue
        texts = []
        for tf in sorted(env.glob("*.tf")):
            text, own = _split_backend(tf.read_text(encoding="utf-8"))
            texts.append(text)
            # an env's own key may differ from its dir name (a dir renumbered
            # with its state kept in place): consumers reference that key
            for k in own:
                key_env.setdefault(k, env.name)
        tfvars = env / "terraform.tfvars.json"
        if tfvars.exists():
            texts.append(tfvars.read_text(encoding="utf-8"))
        blobs[env.name] = "\n".join(texts)
    graph = {}
    for name, blob in blobs.items():
        consumes = set()
        # Only envs that actually declare a remote-state data source consume
        # anything; the key pattern alone could be a comment.
        if 'data "terraform_remote_state"' in blob:
            consumes.update(key_env.get(k, k) for k in _STATE_KEY_RE.findall(blob))
            consumes.update(_LOCAL_PATH_RE.findall(blob))
        consumes.discard(name)
        graph[name] = {"consumes": sorted(consumes)}
    return graph


def check(graph: dict) -> list:
    """LZR-008 ordering violations + unknown references."""
    errs = []
    for env, d in graph.items():
        for dep in d["consumes"]:
            if dep not in graph:
                errs.append(f"{env}: consumes {dep!r} which is not an env directory")
            elif not dep < env:
                errs.append(f"{env}: consumes {dep!r} which does not sort before it "
                            "(producer must apply before consumer - LZR-008)")
    return errs


def apply_order(graph: dict) -> list:
    """Topological order; ties broken by name (= numeric prefix)."""
    order, placed = [], set()
    names = sorted(graph)
    while len(order) < len(names):
        progressed = False
        for n in names:
            if n in placed:
                continue
            if all(d in placed for d in graph[n]["consumes"] if d in graph):
                order.append(n)
                placed.add(n)
                progressed = True
        if not progressed:  # cycle: emit remaining in name order
            order.extend(n for n in names if n not in placed)
            break
    return order


def build(envs_dir: Path) -> dict:
    graph = scan(envs_dir)
    return {
        "#": "Generated by lz_spec/depsgraph.py from terraform_remote_state references. Do not hand-edit.",
        "apply_order": apply_order(graph),
        "envs": graph,
    }
