"""Environment dependency graph (deps.json).

Scans each env's *.tf files for terraform_remote_state references and records
which earlier envs each env consumes. The graph is DERIVED from the code -
never hand-edited - and gives runners/docs a machine-readable apply order.

Rule LZR-008: a consumed env must sort strictly BEFORE its consumer (numeric
directory prefix). An inversion is exactly the class of bug behind the old
06/07 double-apply and fails the check.

Usage:
    py -m lz_pipeline deps --envs-dir <envs>
"""

import re
from pathlib import Path

# A consumed state key, wherever it appears: as a literal in a
# terraform_remote_state config, as a variables.tf default, or as a tfvars
# value (the envs wire keys through variables, e.g.
#   variable "network_state_key" { default = "envs/05-network/terraform.tfstate" }).
_STATE_KEY_RE = re.compile(r'envs/([0-9]{2}-[a-z0-9-]+)/terraform\.tfstate')
# local-backend remote state: path = "../00-bootstrap/terraform.tfstate"
_LOCAL_PATH_RE = re.compile(r'"\.\./([0-9]{2}-[a-z0-9-]+)/terraform\.tfstate"')


def scan(envs_dir: Path) -> dict:
    """{env_name: {"consumes": [env, ...]}} for every env dir, in order."""
    graph = {}
    for env in sorted(p for p in envs_dir.iterdir() if p.is_dir()):
        if not re.match(r"^[0-9]{2}-", env.name):
            continue
        # backend.tf holds only the env's OWN state key (which may differ from
        # the dir name when a dir is renamed but its state kept canonical), never
        # a consumed key - exclude it so it can't read as a self-dependency.
        texts = [tf.read_text(encoding="utf-8")
                 for tf in sorted(env.glob("*.tf")) if tf.name != "backend.tf"]
        tfvars = env / "terraform.tfvars.json"
        if tfvars.exists():
            texts.append(tfvars.read_text(encoding="utf-8"))
        blob = "\n".join(texts)
        consumes = set()
        # Only envs that actually declare a remote-state data source consume
        # anything; the key pattern alone could be a comment or its own backend.
        if 'data "terraform_remote_state"' in blob:
            consumes.update(_STATE_KEY_RE.findall(blob))
            consumes.update(_LOCAL_PATH_RE.findall(blob))
        consumes.discard(env.name)
        graph[env.name] = {"consumes": sorted(consumes)}
    return graph


def check(graph: dict) -> list:
    """LZR-008 ordering violations + unknown references."""
    errs = []
    for env, d in graph.items():
        for dep in d["consumes"]:
            if dep not in graph:
                errs.append(f"{env}: consumes {dep!r} which is not an env directory")
            elif not dep < env:
                errs.append(f"{env}: consumes {dep!r} which does not sort before it "
                            "(producer must apply before consumer - LZR-008)")
    return errs


def apply_order(graph: dict) -> list:
    """Topological order; ties broken by name (= numeric prefix)."""
    order, placed = [], set()
    names = sorted(graph)
    while len(order) < len(names):
        progressed = False
        for n in names:
            if n in placed:
                continue
            if all(d in placed for d in graph[n]["consumes"] if d in graph):
                order.append(n)
                placed.add(n)
                progressed = True
        if not progressed:  # cycle: emit remaining in name order
            order.extend(n for n in names if n not in placed)
            break
    return order


def build(envs_dir: Path) -> dict:
    graph = scan(envs_dir)
    return {
        "#": "Generated by lz_spec/depsgraph.py from terraform_remote_state references. Do not hand-edit.",
        "apply_order": apply_order(graph),
        "envs": graph,
    }
