"""Profile-driven customer artifact export (release v2).

Extends the legacy exporter with:
  - customer PROFILES: feature flags applied at GENERATION time (a feature
    disabled in the profile is stripped from the staged artifact) - so exports
    are always re-runnable and in-place artifact surgery is never needed again;
  - a RUNNER: lzctl.py + plan_triage.py + deps.json ship in the artifact;
  - RELEASE metadata: VERSION, CHANGELOG.md generated from the spec-IR diff
    against the previous release snapshot, and a MANIFEST carrying the
    pipeline/schema coordinates.

--compat reproduces the legacy artifact byte-for-byte (no runner, no release
files) and exists for the oracle test against the shipped tree.

The Excel LLD workbook is generated from the profile's own spec IR into the
artifact root, so every profile ships one and it always matches the spec that
produced the envs (--no-workbook opts out).

Usage:
    py -m lz_pipeline.export_v2 --profile profiles/acme.json --target <dir>
        [--version 1.1.0] [--compat] [--no-workbook]

Profile:
    {"customer": "acme-corp",
     "features": {"secmaster": false},
     "envs_dir": "envs",       # relative to workspace root
     "docs_dir": "handover-docs",
     "ir": "lz_spec/lz.spec.acme.json"}
"""

import argparse
import datetime
import hashlib
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

from . import model

# Workspace root: profile paths (envs_dir/docs_dir/ir) resolve against the
# invoking workspace, not the package location.
ROOT = Path.cwd()
PKG = Path(__file__).resolve().parent
REPO = PKG.parent.parent                    # pipeline/lz_pipeline -> repo root
MODULES = REPO / "terraform" / "modules"


# ────────────────────────────────────────────────────────────────────────────
# Artifact copy/rewrite: paths, generated-file renames, prose rewrites, and
# the exclusion sets (secrets, plan/backup litter, runner residue).
# ────────────────────────────────────────────────────────────────────────────

# generated fan-outs become ordinary files in the artifact; names that would
# collide with existing static files get an -accounts suffix
GENERATED_RENAMES = {
    "providers.generated.tf":     "providers-accounts.tf",
    "outputs.generated.tf":       "outputs-accounts.tf",
    "spokes.generated.tf":        "spokes.tf",
    "tagging.generated.tf":       "tagging.tf",
    "config.generated.tf":        "config.tf",
    "iam-baseline.generated.tf":  "iam-baseline.tf",
    "app-permission-sets.generated.tf": "app-permission-sets.tf",
    "cost-centers.generated.tf":  "cost-centers.tf",
    "observability.generated.tf": "observability.tf",
    "logconverge.generated.tf":   "logconverge.tf",
    "vpn.generated.tf":           "vpn.tf",
    "sgacl.generated.tf":         "sgacl.tf",
}

EXCLUDE_NAMES = {"secrets.auto.tfvars.json", "errored.tfstate", "tf.plan",
                 ".lzctl.lock", ".gitignore"}
# plan files embed variable values (incl. secrets) - never ship any of them;
# .txt: stray plan/log captures
EXCLUDE_SUFFIXES = (".bak", ".backup", ".ps1", ".py", ".xlsx", ".txt",
                    ".tfplan", ".log")
EXCLUDE_DIRS = {".terraform", "__pycache__", "lzctl-logs", "state-backups"}

PROSE_REWRITES = [("# The actual module calls + cross-account provider aliases are GENERATED by\n# build_envs.py into cost-centers.generated.tf and providers.generated.tf\n# (one per account named in the CostCenters sheet's Accounts column). This file\n# only wires the foundation remote state those generated aliases depend on.", '# The module calls + cross-account provider aliases live in cost-centers.tf\n# and providers-accounts.tf (one per target account). This file only wires\n# the foundation remote state those aliases depend on.'), ('# Generated by build_envs.py from the M1 account list into:\n#   providers.generated.tf    (one alias per account)\n#   iam-baseline.generated.tf (master + one module call per account)\n# Add/remove accounts in the 01_Foundation sheet, then re-run build_envs.', '# Per-account fan-out files:\n#   providers-accounts.tf (one alias per account)\n#   iam-baseline.tf       (master + one module call per account)\n# To add or remove an account, copy or delete the matching blocks\n# (see cookbooks/add-account.md).'), ('# Spoke providers + per-VPC module calls are GENERATED (spokes.generated.tf /\n# providers.generated.tf) from the SpokeVPCs table by build_envs.py.', '# Spoke providers + per-VPC module calls live in spokes.tf and\n# providers-accounts.tf (one pair per spoke VPC).'), ('# The central audit module (CTS-admin account) and the per-account ops modules are\n# generated by build_envs.py into providers.generated.tf + observability.generated.tf\n# (one audit call + one ops call per OpsSettings.accounts entry). Do not add module\n# calls here.', '# The central audit module (CTS-admin account) and the per-account ops modules\n# live in providers-accounts.tf + observability.tf (one audit call + one ops\n# call per account). Add or remove module calls there, not here.'), ('# Per-account assume_role providers (audit_admin + ops accounts) are generated by\n# build_envs.py into providers.generated.tf.', '# Per-account assume_role providers (audit_admin + ops accounts) live in\n# providers-accounts.tf.'), ('# envs-v2/03-identity', '# 03-identity'), ('# Wraps modules-v2/organization (relative path).', '# Wraps the organization module (relative path).'), ('modules-v2/perimeter/variables.tf', 'modules/perimeter/variables.tf')]

# source-tree module path -> artifact-relative path
PATH_REWRITE = ("../../../huaweicloud-agentic-tools/modules-v2/", "../../modules/")


def excluded(p: Path, exclude_names: set) -> bool:
    if p.name in exclude_names:
        return True
    if any(p.name.endswith(s) for s in EXCLUDE_SUFFIXES):
        return True
    # env-local state stays out EXCEPT the bootstrap state (local backend);
    # state-*.json covers the runbooks' `terraform state pull > state-...json`
    # backup convention in every spelling.
    if p.name.startswith("terraform.tfstate") and p.parent.name != "00-bootstrap":
        return True
    if p.name.startswith("state-") and p.name.endswith(".json"):
        return True
    if p.name.endswith(".pre-rename.backup"):
        return True
    return False


def copy_tree(src: Path, dst: Path, rewrite: bool, exclude_names: set = EXCLUDE_NAMES):
    n = 0
    for p in sorted(src.rglob("*")):
        if p.is_dir() or any(d in p.parts for d in EXCLUDE_DIRS) or excluded(p, exclude_names):
            continue
        rel = p.relative_to(src)
        name = GENERATED_RENAMES.get(rel.name, rel.name)
        out = dst / rel.parent / name
        out.parent.mkdir(parents=True, exist_ok=True)
        if rewrite and p.suffix in (".tf", ".md"):
            text = p.read_text(encoding="utf-8")
            text = text.replace(*PATH_REWRITE)
            for old_txt, new_txt in PROSE_REWRITES:
                text = text.replace(old_txt, new_txt)
            # generated filenames mentioned in comments -> artifact names
            for gname, plain in GENERATED_RENAMES.items():
                text = text.replace(gname, plain)
            if rel.name in GENERATED_RENAMES:
                text = text.replace(
                    "# GENERATED by build_envs.py - do not edit.",
                    "# Per-account fan-out. Ordinary Terraform: edit by hand (copy an existing\n"
                    "# block to add an account; delete a block to remove one).",
                )
            out.write_text(text, encoding="utf-8")
        else:
            shutil.copy2(p, out)
        n += 1
    return n


# ────────────────────────────────────────────────────────────────────────────
# Feature strip: what disabling secmaster removes from envs/07-security.
# Spans were derived from - and are oracle-tested against - the reviewed
# removal in the shipped artifact.
# ────────────────────────────────────────────────────────────────────────────

def _find_block(text: str, header_re: str):
    """(start, end) of the block whose opening line matches header_re; the
    span runs to the matching closing brace, inclusive of the trailing \\n."""
    m = re.search(header_re, text)
    if not m:
        return None
    i = text.index("{", m.start())
    depth = 0
    for j in range(i, len(text)):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                end = j + 1
                if end < len(text) and text[end] == "\n":
                    end += 1
                return m.start(), end
    return None


def strip_secmaster(env_dir: Path):
    """Remove the SecMaster wiring from envs/07-security. Fails CLOSED: a
    pattern that finds nothing means the env drifted from this strip -
    shipping would leave a "disabled" billable feature in the artifact."""

    def _file(name):
        p = env_dir / name
        if not p.exists():
            print(f"  strip[secmaster]: skip {name}: not present")
            return None
        return p

    def _fail(name, what):
        raise SystemExit(f"feature secmaster=off strip incomplete ({name}: {what} "
                         f"not found) - update strip_secmaster in export_v2.py "
                         f"to match envs/{env_dir.name}")

    def _drop_block(text, header_re, name):
        span = _find_block(text, header_re)
        if span is None:
            _fail(name, f"block {header_re!r}")
        s, e = span
        if s >= 1 and text[s - 1] == "\n" and (s < 2 or text[s - 2] == "\n"):
            s -= 1
        return text[:s] + text[e:]

    def _drop_span(text, start_re, end_re, name):
        ms = re.search(start_re, text, re.M)
        me = re.search(end_re, text[ms.start():], re.M) if ms else None
        if ms is None or me is None:
            _fail(name, f"span {start_re!r}")
        end = ms.start() + me.end()
        if end < len(text) and text[end] == "\n":
            end += 1
        return text[:ms.start()] + text[end:]

    p = _file("main.tf")
    if p:
        text = p.read_text(encoding="utf-8")
        text = _drop_block(text, r'data "terraform_remote_state" "observability" \{', p.name)
        text = "\n".join(l for l in text.split("\n") if not re.match(
            r'^  observability = data\.terraform_remote_state\.observability\.outputs$', l))
        text = _drop_span(text, r'^\n  # Wire SecMaster cloud_log_resources', r'^  \]$', p.name)
        text = _drop_span(text, r'^\n# Warn \(not fail\) when SecMaster deploys', r'^\}$', p.name)
        text = _drop_block(text, r'module "security" \{', p.name)
        # the reviewed artifact keeps a separating blank line in locals
        text = text.replace("network       = data.terraform_remote_state.network.outputs\n}",
                            "network       = data.terraform_remote_state.network.outputs\n\n}")
        p.write_text(text, encoding="utf-8")

    p = _file("variables.tf")
    if p:
        text = p.read_text(encoding="utf-8")
        for name in ("observability_state_bucket", "observability_state_key",
                     "security_account", "enable_secmaster", "secmaster_workspace_name",
                     "secmaster_modules", "alert_rules", "enable_hss", "enable_dbss",
                     "enable_member_workspaces", "member_workspace_bindings"):
            span = _find_block(text, rf'variable "{name}" \{{')
            if span:
                text = text[:span[0]] + text[span[1]:]
        text = re.sub(r"\n{4,}", "\n\n\n", text)
        p.write_text(text, encoding="utf-8")

    p = _file("outputs.tf")
    if p:
        text = p.read_text(encoding="utf-8").replace(
            'output "secmaster_workspace_id" { value = module.security.secmaster_workspace_id }',
            "# No outputs: edge protection exposes nothing downstream.")
        p.write_text(text, encoding="utf-8")

    p = _file("providers.tf")
    if p:
        text = _drop_block(p.read_text(encoding="utf-8"),
                           r'provider "huaweicloud" \{\n  alias              = "lz_security"',
                           p.name)
        p.write_text(text, encoding="utf-8")

    p = _file("terraform.tfvars.json")
    if p:
        data = json.loads(p.read_text(encoding="utf-8"))
        for k in ("observability_state_bucket", "secmaster_modules", "security_account"):
            data.pop(k, None)
        p.write_text(json.dumps(data, indent=2, sort_keys=False) + "\n", encoding="utf-8")

    p = _file("terraform.tfvars.example")
    if p:
        match = (r'^(observability_state_bucket|# enable_secmaster|# enable_hss|# enable_dbss'
                 r'|# enable_member_workspaces|# member_workspace_bindings)')
        text = "\n".join(l for l in p.read_text(encoding="utf-8").split("\n")
                         if not re.match(match, l))
        p.write_text(text, encoding="utf-8")


# ────────────────────────────────────────────────────────────────────────────
# Release metadata
# ────────────────────────────────────────────────────────────────────────────

def _row_key(row: dict):
    for k in ("Name", "VPCName", "Policy", "UserName", "Package", "Domain", "Namespace",
              "Account", "Key", "Zone", "Endpoint"):
        if row.get(k):
            return str(row[k])
    return json.dumps(row, sort_keys=True)[:60]


def spec_changelog(prev: dict, cur: dict) -> list:
    lines = []
    ps, cs = prev.get("sheets", {}), cur.get("sheets", {})
    for sheet in sorted(set(ps) | set(cs)):
        pt, ct = ps.get(sheet) or {}, cs.get(sheet) or {}
        for table in sorted(set(pt) | set(ct)):
            a, b = pt.get(table), ct.get(table)
            if a == b:
                continue
            if isinstance(a, dict) or isinstance(b, dict):
                a, b = a or {}, b or {}
                for k in sorted(set(a) | set(b)):
                    if a.get(k) != b.get(k):
                        lines.append(f"- {sheet}.{table}.{k}: {a.get(k)!r} -> {b.get(k)!r}")
            elif isinstance(a, list) or isinstance(b, list):
                if a and isinstance(a[0], dict) or b and isinstance(b[0], dict):
                    ka = {_row_key(r): r for r in (a or [])}
                    kb = {_row_key(r): r for r in (b or [])}
                    for k in sorted(set(kb) - set(ka)):
                        lines.append(f"- {sheet}.{table}: added {k!r}")
                    for k in sorted(set(ka) - set(kb)):
                        lines.append(f"- {sheet}.{table}: removed {k!r}")
                    for k in sorted(set(ka) & set(kb)):
                        if ka[k] != kb[k]:
                            lines.append(f"- {sheet}.{table}: changed {k!r}")
                else:
                    lines.append(f"- {sheet}.{table}: list changed "
                                 f"({len(a or [])} -> {len(b or [])} entries)")
    return lines


# ────────────────────────────────────────────────────────────────────────────
# Export
# ────────────────────────────────────────────────────────────────────────────

def export(profile: dict, target: Path, version: str, compat: bool,
           releases_dir: Path, no_workbook: bool = False) -> int:
    envs = ROOT / profile["envs_dir"]
    docs_rel = profile.get("docs_dir")
    docs = (ROOT / docs_rel) if docs_rel else None
    ir_path = ROOT / profile["ir"] if profile.get("ir") else None

    # deps.json ships except in compat mode
    exclude_names = EXCLUDE_NAMES | {"deps.json"} if compat else EXCLUDE_NAMES

    # Clear CONTENTS but keep the target directory itself: removing the root
    # fails with PermissionError when any process holds the folder open, and
    # rmtree deletes children before dying - a half-gutted artifact. Deleting
    # per-child leaves the root handle untouched.
    if target.exists():
        children = list(target.iterdir())
        # Data-loss guard: only clear a directory that is empty or provably a
        # previous export (carries our marker files). Refuses --target ., the
        # repo root, a source envs tree, or any other populated directory.
        if children and not any((target / m).exists()
                                for m in ("MANIFEST.txt", "VERSION")):
            raise SystemExit(
                f"refusing to clear {target}: it contains files but no previous "
                "export (MANIFEST.txt/VERSION) - use an empty or dedicated "
                "artifact directory")
        for child in children:
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()
    else:
        target.mkdir(parents=True)

    n_mod = copy_tree(MODULES, target / "modules", rewrite=True, exclude_names=exclude_names)
    n_env = copy_tree(envs, target / "envs", rewrite=True, exclude_names=exclude_names)
    n_doc = 0
    wb_copied = False
    if docs is not None and docs.exists():
        n_doc = copy_tree(docs, target, rewrite=False, exclude_names=exclude_names)
        if (docs / ".gitignore").exists():
            shutil.copy2(docs / ".gitignore", target / ".gitignore")
            n_doc += 1
        # A workbook already sitting in docs_dir is superseded by the generated
        # one below; copy it only as a fallback for profiles that carry no IR.
        wb = docs / "landing-zone-spec.xlsx"
        if wb.exists():
            shutil.copy2(wb, target / wb.name)
            n_doc += 1
            wb_copied = True

    # The Excel LLD workbook is a first-class artifact, GENERATED from this
    # profile's own spec IR - so every profile ships one, always matching the
    # spec that produced the envs (a docs_dir copy could be stale or another
    # customer's).
    if not no_workbook and ir_path and ir_path.exists():
        out_wb = target / "landing-zone-spec.xlsx"
        r = subprocess.run([sys.executable, "-X", "utf8", "-m", "lz_pipeline.tools.gen_workbook",
                            "--ir", str(ir_path), "-o", str(out_wb)],
                           capture_output=True, text=True, encoding="utf-8",
                           errors="replace", cwd=str(ROOT))
        if r.returncode != 0:
            print(r.stdout[-600:], r.stderr[-600:])
            print("FAIL: workbook generation failed")
            return 1
        if not out_wb.exists():
            print("FAIL: workbook was not written")
            return 1
        if not wb_copied:
            n_doc += 1
        print(f"  workbook: generated from {ir_path.name}")

    # feature strip
    feats = profile.get("features") or {}
    if "secmaster" in feats and not feats["secmaster"]:
        strip_secmaster(target / "envs" / "07-security")
        print("  feature secmaster=off: stripped from envs/07-security")

    # runner + release metadata (not in compat mode)
    if not compat:
        runner = target / "runner"
        runner.mkdir()
        shutil.copy2(PKG / "lzctl.py", runner / "lzctl.py")
        shutil.copy2(PKG / "tools" / "plan_triage.py", runner / "plan_triage.py")
        pricing_src = PKG / "tools" / "pricing"
        if pricing_src.exists():
            shutil.copytree(pricing_src, runner / "pricing")
        (runner / "README.md").write_text(
            "# lzctl - the landing-zone runner\n\n"
            "Requires Python 3.10+ and terraform on PATH. Start with:\n\n"
            "    py lzctl.py preflight --envs-dir ..\\envs\n"
            "    py lzctl.py plan --envs-dir ..\\envs --all\n\n"
            "See the root README and cookbooks for the operating procedures.\n",
            encoding="utf-8")

        (target / "VERSION").write_text(version + "\n", encoding="utf-8")

        changelog = [f"# Release {version} - {datetime.date.today().isoformat()}", ""]
        if ir_path and ir_path.exists():
            cur = model.load(ir_path)
            prev_release = None
            rels = releases_dir / profile["customer"]
            if rels.exists():
                versions = sorted((d.name for d in rels.iterdir() if d.is_dir()),
                                  key=lambda v: [int(x) for x in re.findall(r"\d+", v)] or [0])
                if versions:
                    prev_release = versions[-1]
            if prev_release:
                prev = model.load(rels / prev_release / "lz.spec.json")
                delta = spec_changelog(prev, cur)
                changelog += [f"Changes against release {prev_release}:", ""]
                changelog += delta if delta else ["- no specification changes (pipeline/module release)"]
            else:
                changelog += ["Initial release."]
            snap = rels / version
            snap.mkdir(parents=True, exist_ok=True)
            model.save(cur, snap / "lz.spec.json")
        else:
            changelog += ["(no spec IR referenced in the profile - changelog not derived)"]
        (target / "CHANGELOG.md").write_text("\n".join(changelog) + "\n", encoding="utf-8")

    # manifest
    from lz_spec import schema as wb_schema
    header = [f"# Handover artifact - exported {datetime.date.today().isoformat()} by export_v2",
              "# Regenerate with: py -m lz_pipeline.export_v2 --profile <profile> --target <dir>"]
    if not compat:
        header += [f"# customer: {profile['customer']}  version: {version}  "
                   f"schema: {wb_schema.SCHEMA_VERSION}",
                   "# features: " + json.dumps(profile.get("features") or {})]
    manifest = header + [""]
    for p in sorted(target.rglob("*")):
        if p.is_file() and p.name != "MANIFEST.txt":
            digest = hashlib.sha256(p.read_bytes()).hexdigest()[:16]
            manifest.append(f"{digest}  {p.relative_to(target).as_posix()}")
    (target / "MANIFEST.txt").write_text("\n".join(manifest) + "\n", encoding="utf-8")

    print(f"exported: {n_mod} module files, {n_env} env files, {n_doc} doc files -> {target}")
    return 0


def main(argv=None):
    import os
    ap = argparse.ArgumentParser(prog=os.environ.get("LZ_INVOKED_AS") or None)
    ap.add_argument("--profile", required=True)
    ap.add_argument("--target", required=True)
    ap.add_argument("--version", default="1.0.0")
    ap.add_argument("--compat", action="store_true",
                    help="legacy-identical output (no runner/release files)")
    ap.add_argument("--no-workbook", action="store_true",
                    help="skip generating landing-zone-spec.xlsx into the artifact")
    ap.add_argument("--releases-dir", default=str(ROOT / "releases"))
    args = ap.parse_args(argv)
    profile = json.loads(Path(args.profile).read_text(encoding="utf-8"))
    return export(profile, Path(args.target), args.version, args.compat,
                  Path(args.releases_dir), args.no_workbook)


if __name__ == "__main__":
    sys.exit(main())
