# GENERATED by build_envs.py - do not edit.
output "spoke_vpc_ids" {
  description = "Spoke VPC IDs keyed by VPC name."
  value = {
    "example-prod-a-vpc" = module.spoke_example_prod_a_vpc.spoke_vpc_id
    "example-sbx-vpc" = module.spoke_example_sbx_vpc.spoke_vpc_id
  }
}
