# 03-identity
#
# IC content (1 call to module 2 in master) +
# IAM baseline per-account (1 call per created account, via provider alias).
#
# Add/remove accounts by:
#   1. Adding a provider alias in providers.tf
#   2. Adding a module "iam_baseline_<alias>" block below
#
# Pattern C: provider aliases are explicit, not generated dynamically (Terraform
# does not support for_each over module providers).

# ── Read module 1 outputs from remote state ────────────────────────────────

data "terraform_remote_state" "foundation" {
  backend = "s3"
  config = {
    bucket                      = var.foundation_state_bucket
    key                         = var.foundation_state_key
    region                      = var.home_region
    endpoints                   = { s3 = "https://obs.${var.home_region}.myhuaweicloud.com" }
    access_key                  = var.master_access_key
    secret_key                  = var.master_secret_key
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    skip_region_validation      = true
    skip_credentials_validation = true
    skip_metadata_api_check     = true
  }
}

locals {
  foundation = data.terraform_remote_state.foundation.outputs
}

# ── IC content (master account, default provider) ─────────────────────────

module "ic_content" {
  source = "../../modules/identity"

  environment                    = var.environment
  enable_identity_center_content = true
  enable_iam_baseline            = false

  identity_store_id           = local.foundation.identity_store_id
  identity_center_instance_id = local.foundation.identity_center_instance_id

  # Pass var if user overrides; else module 2 defaults apply.
  groups              = var.groups != null ? var.groups : null
  users               = var.users != null ? var.users : null
  permission_sets     = var.permission_sets != null ? var.permission_sets : null
  account_assignments = var.account_assignments # empty = no assignments
  registered_regions  = var.registered_regions

  session_duration   = var.session_duration
  ic_password_policy = var.ic_password_policy
  ic_mfa_management  = var.ic_mfa_management
}

# ── IAM baseline (per-account) ─────────────────────────────────────────────
# Generated by build_envs.py from the M1 account list into:
#   providers.generated.tf    (one alias per account)
#   iam-baseline.generated.tf (master + one module call per account)
# Add/remove accounts in the 01_Foundation sheet, then re-run build_envs.
