# GENERATED by build_envs.py - do not edit.
# Provider alias per M1 account (master uses the default provider).

provider "huaweicloud" {
  alias              = "acct_EXAMPLE_LogArchive"
  region             = var.home_region
  access_key         = var.master_access_key
  secret_key         = var.master_secret_key
  domain_name        = local.foundation.master_account_name
  domain_id          = local.foundation.accounts["EXAMPLE-LogArchive"].id
  agency_name        = local.foundation.cross_account_agency_name
  agency_domain_name = "EXAMPLE-LogArchive"
  default_tags       = var.default_tags
}

provider "huaweicloud" {
  alias              = "acct_EXAMPLE_Security"
  region             = var.home_region
  access_key         = var.master_access_key
  secret_key         = var.master_secret_key
  domain_name        = local.foundation.master_account_name
  domain_id          = local.foundation.accounts["EXAMPLE-Security"].id
  agency_name        = local.foundation.cross_account_agency_name
  agency_domain_name = "EXAMPLE-Security"
  default_tags       = var.default_tags
}

provider "huaweicloud" {
  alias              = "acct_EXAMPLE_SharedInfra"
  region             = var.home_region
  access_key         = var.master_access_key
  secret_key         = var.master_secret_key
  domain_name        = local.foundation.master_account_name
  domain_id          = local.foundation.accounts["EXAMPLE-SharedInfra"].id
  agency_name        = local.foundation.cross_account_agency_name
  agency_domain_name = "EXAMPLE-SharedInfra"
  default_tags       = var.default_tags
}

provider "huaweicloud" {
  alias              = "acct_EXAMPLE_Prod_A"
  region             = var.home_region
  access_key         = var.master_access_key
  secret_key         = var.master_secret_key
  domain_name        = local.foundation.master_account_name
  domain_id          = local.foundation.accounts["EXAMPLE-Prod-A"].id
  agency_name        = local.foundation.cross_account_agency_name
  agency_domain_name = "EXAMPLE-Prod-A"
  default_tags       = var.default_tags
}

provider "huaweicloud" {
  alias              = "acct_EXAMPLE_Sandbox1"
  region             = var.home_region
  access_key         = var.master_access_key
  secret_key         = var.master_secret_key
  domain_name        = local.foundation.master_account_name
  domain_id          = local.foundation.accounts["EXAMPLE-Sandbox1"].id
  agency_name        = local.foundation.cross_account_agency_name
  agency_domain_name = "EXAMPLE-Sandbox1"
  default_tags       = var.default_tags
}
