# GENERATED by build_envs.py - do not edit.
# VPN (10_VPN sheet): S2C gateways attach to the 05-network hub VPC/ER,
# resolved via remote state (local.network). Apply 05-network first.

module "vpn" {
  source    = "../../modules/vpn"
  providers = { huaweicloud = huaweicloud.vpn }

  enterprise_project_id = local.enterprise_project_id

  vpc_ids = merge(local.network.hub_vpc_ids, {
    "example-prod-a-vpc" = local.network.spoke_vpc_ids["example-prod-a-vpc"]
    "example-sbx-vpc" = local.network.spoke_vpc_ids["example-sbx-vpc"]
  })
  subnet_ids         = local.network.hub_subnet_ids
  er_id              = local.network.er_id
  er_route_table_ids = local.network.route_table_ids

  gateways          = var.gateways
  customer_gateways = var.customer_gateways
  connections       = var.connections
}
