# GENERATED by build_envs.py - do not edit.
# Cost-center EP IDs keyed by target account.

output "cost_center_ep_ids_by_account" {
  description = "Map of account -> { cost-center EP name -> EP ID }."
  value = {
    "master" = module.cost_centers_master.cost_center_ep_ids
    "EXAMPLE-LogArchive" = module.cost_centers_acct_EXAMPLE_LogArchive.cost_center_ep_ids
    "EXAMPLE-Security" = module.cost_centers_acct_EXAMPLE_Security.cost_center_ep_ids
    "EXAMPLE-SharedInfra" = module.cost_centers_acct_EXAMPLE_SharedInfra.cost_center_ep_ids
    "EXAMPLE-Prod-A" = module.cost_centers_acct_EXAMPLE_Prod_A.cost_center_ep_ids
    "EXAMPLE-Sandbox1" = module.cost_centers_acct_EXAMPLE_Sandbox1.cost_center_ep_ids
  }
}
