"""IAM 5 actions that support g:EnterpriseProjectId, per service.

Extracted 2026-08-01 from the Huawei IAM 5 service-authorization reference
(support.huaweicloud.com/intl/en-us/service-authorization-iam5/<page>; DNS from
api-dns/Permission.html). An action is listed iff its Condition Key column
includes g:EnterpriseProjectId. Long tables were parsed from the raw HTML
(rowspan-aware), not summarized. Feeds the LLD EP_Scoping glossary sheet and
EP-scoped permission-set policy assembly.

Services checked with NO (or one) qualifying action: AOM (none),
LTS (only lts:logStream:createLogStream). ECS is nearly unscoped: only the 9
actions below of ~100 carry the key — most ECS mutations (start/stop/delete)
CANNOT be EP-conditioned.
"""

# The curated minimal subset used for EP-scoped permission-set policies: only
# the per-main-resource entry gate — the detail read the console needs to open
# a resource. Denying the gate blocks console access to out-of-scope resources
# entirely; direct-API mutations on known IDs are NOT blocked by this tier
# (see EP_ACTIONS for what more a service could enforce). Exceptions to the
# one-gate rule: FunctionGraph's detail read is split config+code; OBS needs
# listBucket (browse contents) beside headBucket; csms:secret:getVersion
# returns the secret VALUE, which is access in itself. IMS and LTS have no
# EP-bindable gate at all. Every entry must exist in EP_ACTIONS (asserted
# below).
ESSENTIAL_ACTIONS = {
    "ecs:cloudServers:showServer",
    "evs:volumes:get",
    "cbr:vaults:get", "cbr:backups:get",
    # vpc:securityGroups:get deliberately absent: it aliases
    # vpc:securityGroups:list, and denying it breaks the SG console list under
    # "All enterprise projects" (validator USING_ALIAS_IN_ACTION_OF_DENY).
    "vpc:vpcs:get",
    "eip:publicIps:get",
    "nat:natGateways:get",
    "elb:loadbalancers:show",
    "dns:zone:get",
    "rds:instance:get",
    "obs:bucket:headBucket", "obs:bucket:listBucket",
    "sfsturbo:shares:getShare",
    "as:scalingGroup:get",
    "functiongraph:function:getFunctionConfig", "functiongraph:function:getFunctionCode",
    "smn:topic:get",
    "ces:alarms:get",
    "kms:cmk:get",
    "csms:secret:get", "csms:secret:getVersion",
}

EP_ACTIONS = {
    "ecs": {  # iam_11_0007
        "actions": [
            "ecs:cloudServers:createServers", "ecs:cloudServers:resize",
            "ecs:cloudServers:showServer", "ecs:cloudServers:detachVolume",
            "ecs:cloudServers:listServersDetails", "ecs:cloudServers:resetServerPwd",
            "ecs:cloudServers:showMetadataOptions", "ecs:cloudServers:updateMetadataOptions",
            "ecs:cloudServers:changeNetworkInterface",
        ],
    },
    "ims": {  # iam_11_0008
        "actions": [
            "ims:images:list", "ims:images:share", "ims:images:copyInRegion",
            "ims:images:copyCrossRegion", "ims:images:upload", "ims:wholeImages:create",
            "ims:images:export", "ims:dataImages:create", "ims:serverImages:create",
            "ims:images:setTags", "ims:images:getTags", "ims:images:deleteImage",
            "ims:images:updateImage", "ims:images:import", "ims:images:getMember",
            "ims:images:listMember", "ims:images:deleteTags", "ims:images:addMember",
            "ims:images:deleteMember", "ims:cloudServerImages:create",
            "ims:cloudDataImages:create", "ims:cloudImages:import",
            "ims:cloudImages:copyInRegion", "ims:images:showImageTags",
        ],
    },
    "as": {  # iam_11_0005
        "actions": [
            "as:scalingGroup:create", "as:scalingGroup:delete", "as:scalingGroup:list",
            "as:scalingGroup:get", "as:scalingGroup:update", "as:scalingGroup:resume",
            "as:scalingGroup:pause", "as:scalingGroup:batchAddInstances",
            "as:scalingGroup:batchRemoveInstances", "as:scalingGroup:batchSetInstancesProtect",
            "as:scalingGroup:batchSetInstancesUnprotect", "as:scalingGroup:batchSetInstancesStandby",
            "as:scalingGroup:batchSetInstancesExitStandby", "as:scalingGroup:deleteInstance",
            "as:scalingGroup:listInstances", "as:scalingPolicy:create", "as:scalingPolicy:list",
            "as:scalingPolicy:get", "as:scalingPolicy:update", "as:scalingPolicy:delete",
            "as:scalingPolicy:execute", "as:scalingPolicy:resume", "as:scalingPolicy:pause",
            "as:scalingPolicy:batchPause", "as:scalingPolicy:batchResume",
            "as:scalingPolicy:batchDelete", "as:scalingPolicy:listAll",
            "as:scalingGroup:listActivityLogs", "as:scalingPolicy:listExecuteLogs",
            "as::tagResource", "as::untagResource", "as::listTagsForResource",
            "as:scalingGroup:createLifecycleHook", "as:scalingGroup:listLifecycleHooks",
            "as:scalingGroup:getLifecycleHook", "as:scalingGroup:updateLifecycleHook",
            "as:scalingGroup:deleteLifecycleHook", "as:scalingGroup:callbackInstanceHook",
            "as:scalingGroup:listInstanceHooks", "as:scalingGroup:createNotification",
            "as:scalingGroup:listNotifications", "as:scalingGroup:deleteNotification",
            "as:scalingGroup:getQuotas",
        ],
    },
    "functiongraph": {  # iam_11_0009
        "actions": [
            "functiongraph:function:createFunction", "functiongraph:function:deleteFunction",
            "functiongraph:function:listFunctions", "functiongraph:function:getFunctionCode",
            "functiongraph:function:updateFunctionCode", "functiongraph:function:getFunctionConfig",
            "functiongraph:function:updateFunctionConfig", "functiongraph:function:updateMaxInstanceConfig",
            "functiongraph:function:updateSnapshot", "functiongraph:function:getSnapshotState",
            "functiongraph:function:createUrl", "functiongraph:function:deleteUrl",
            "functiongraph:function:updateUrl", "functiongraph:function:getUrl",
            "functiongraph::getResourceInstance", "functiongraph::createTag",
            "functiongraph::deleteTag", "functiongraph::listTags",
            "functiongraph::createFunctionApp", "functiongraph::deleteFunctionApp",
            "functiongraph::getFunctionApp", "functiongraph::listFunctionApps",
            "functiongraph::listFunctionAppTemplates", "functiongraph::createVpcEndpoint",
            "functiongraph::deleteVpcEndpoint", "functiongraph:function:export",
            "functiongraph:function:import", "functiongraph::exportPackage",
            "functiongraph::importPackage", "functiongraph:function:createVersion",
            "functiongraph:function:listVersion", "functiongraph:function:createAlias",
            "functiongraph:function:deleteAlias", "functiongraph:function:listAlias",
            "functiongraph:function:getAlias", "functiongraph:function:updateAlias",
            "functiongraph:function:createEvent", "functiongraph:function:deleteEvent",
            "functiongraph:function:updateEvent", "functiongraph:function:listEvent",
            "functiongraph:function:getEvent", "functiongraph:function:getTracing",
            "functiongraph:function:updateTracing", "functiongraph:function:listFunctionStatistics",
            "functiongraph:function:getReservedInstanceMetrics", "functiongraph:function:getLtsLogConfiguration",
            "functiongraph:function:updateReservedInstanceCount", "functiongraph::listReservedInstanceConfig",
            "functiongraph:function:invokeAsync", "functiongraph:function:invokeSync",
            "functiongraph:function:invokeReservedFunctionAsync", "functiongraph:function:stopAsyncInvoke",
            "functiongraph:function:listAsyncInvocation", "functiongraph:function:deleteAsyncInvokeConfig",
            "functiongraph:function:updateAsyncInvokeConfig", "functiongraph:function:listAsyncInvokeConfig",
            "functiongraph:function:getAsyncInvokeConfig", "functiongraph:function:listActiveAsyncInvocations",
            "functiongraph:trigger:createTrigger", "functiongraph:trigger:delete",
            "functiongraph:trigger:update", "functiongraph:trigger:list",
            "functiongraph:trigger:get", "functiongraph:trigger:batchDelete",
            "functiongraph:workflow:create", "functiongraph:workflow:delete",
            "functiongraph:workflow:update", "functiongraph:workflow:list",
            "functiongraph:workflow:getConfig", "functiongraph:workflow:invoke",
            "functiongraph:workflow:invokeSync", "functiongraph:workflow:terminate",
            "functiongraph:workflow:retry", "functiongraph:workflow:listExecutions",
            "functiongraph:workflow:getExecutionDetail", "functiongraph:workflow:getMetric",
            "functiongraph:workflow:downloadOutput", "functiongraph:workflow:cancel",
        ],
    },
    "evs": {  # iam_11_0013
        "actions": [
            "evs:volumes:create", "evs:volumes:list", "evs:volumes:get", "evs:volumes:delete",
            "evs:volumes:update", "evs:volumes:resize", "evs:volumes:modifyQos",
            "evs:volumes:retype", "evs:volumes:revert", "evs:volumes:changeChargeMode",
            "evs:volumes:use", "evs:volumes:tagResource", "evs:volumes:unTagResource",
            "evs:volumes:listTagsForResource", "evs:snapshots:create", "evs:snapshots:list",
            "evs:snapshots:get", "evs:snapshots:delete", "evs:snapshots:update",
            "evs:snapshots:rollback",
        ],
    },
    "cbr": {  # iam_11_0012
        "actions": [
            "cbr:tasks:list", "cbr:tasks:get", "cbr:backups:import", "cbr:member:create",
            "cbr:member:update", "cbr:member:get", "cbr:member:delete",
            "cbr:vaults:changeChargeMode", "cbr:vaults:syncCapacity", "cbr:vaults:replicate",
            "cbr:vaults:backup", "cbr:vaults:sync", "cbr:vaults:create", "cbr:vaults:list",
            "cbr:vaults:get", "cbr:vaults:update", "cbr:vaults:delete",
            "cbr:vaults:removeResources", "cbr:vaults:addResources", "cbr:vaults:setResources",
            "cbr:vaults:associatePolicy", "cbr:vaults:dissociatePolicy",
            "cbr:vaults:migrateResources", "cbr:vaults:listProtectables",
            "cbr:vaults:updateOrder", "cbr:backups:sync", "cbr:backups:get",
            "cbr:backups:showMetadata", "cbr:backups:list", "cbr:backups:delete",
            "cbr:backups:replicate", "cbr:backups:restore", "cbr:backups:update",
        ],
    },
    "obs": {  # iam_11_0011 - only createBucket and listAllMyBuckets lack the key
        "actions": [
            "obs:bucket:deleteBucket", "obs:bucket:deleteBucketCustomDomainConfiguration",
            "obs:bucket:deleteBucketInventoryConfiguration", "obs:bucket:deleteBucketPolicy",
            "obs:bucket:deleteBucketTagging", "obs:bucket:deleteBucketWebsite",
            "obs:bucket:deleteDirectColdAccessConfiguration", "obs:bucket:deleteReplicationConfiguration",
            "obs:bucket:deleteBucketPublicAccessBlock", "obs:bucket:getBucketAcl",
            "obs:bucket:getBucketObjectLockConfiguration", "obs:bucket:getBucketCORS",
            "obs:bucket:getBucketCustomDomainConfiguration", "obs:bucket:getBucketInventoryConfiguration",
            "obs:bucket:getBucketLocation", "obs:bucket:getBucketLogging",
            "obs:bucket:getBucketPolicy", "obs:bucket:getBucketQuota",
            "obs:bucket:getBucketStorage", "obs:bucket:getBucketStoragePolicy",
            "obs:bucket:getBucketTagging", "obs:bucket:getBucketVersioning",
            "obs:bucket:getBucketWebsite", "obs:bucket:getDirectColdAccessConfiguration",
            "obs:bucket:getEncryptionConfiguration", "obs:bucket:getLifecycleConfiguration",
            "obs:bucket:getReplicationConfiguration", "obs:bucket:getBucketPublicAccessBlock",
            "obs:bucket:getBucketPolicyPublicStatus", "obs:bucket:getBucketPublicStatus",
            "obs:bucket:headBucket", "obs:bucket:listBucket",
            "obs:bucket:listBucketMultipartUploads", "obs:bucket:listBucketVersions",
            "obs:bucket:putBucketAcl", "obs:bucket:putBucketCORS",
            "obs:bucket:putBucketCustomDomainConfiguration", "obs:bucket:putBucketObjectLockConfiguration",
            "obs:bucket:putBucketInventoryConfiguration", "obs:bucket:putBucketLogging",
            "obs:bucket:putBucketPolicy", "obs:bucket:putBucketQuota",
            "obs:bucket:putBucketStoragePolicy", "obs:bucket:putBucketTagging",
            "obs:bucket:putBucketVersioning", "obs:bucket:putBucketWebsite",
            "obs:bucket:putDirectColdAccessConfiguration", "obs:bucket:putEncryptionConfiguration",
            "obs:bucket:putLifecycleConfiguration", "obs:bucket:putReplicationConfiguration",
            "obs:bucket:putBucketPublicAccessBlock", "obs:object:abortMultipartUpload",
            "obs:object:deleteObject", "obs:object:deleteObjectVersion",
            "obs:object:deleteObjectTagging", "obs:object:deleteObjectVersionTagging",
            "obs:object:getObject", "obs:object:getObjectVersion", "obs:object:getObjectAcl",
            "obs:object:getObjectVersionAcl", "obs:object:getObjectTagging",
            "obs:object:getObjectVersionTagging", "obs:object:getObjectRetention",
            "obs:object:listMultipartUploadParts", "obs:object:modifyObjectMetadata",
            "obs:object:putObject", "obs:object:putObjectAcl", "obs:object:putObjectVersionAcl",
            "obs:object:putObjectTagging", "obs:object:putObjectVersionTagging",
            "obs:object:putObjectRetention", "obs:object:restoreObject",
        ],
    },
    "sfsturbo": {  # iam_11_0014
        "actions": [
            "sfsturbo:shares:createShare", "sfsturbo:shares:deleteShare",
            "sfsturbo:shares:getAllShares", "sfsturbo:shares:getShare",
            "sfsturbo:shares:extendShare", "sfsturbo:shares:updateHpcShare",
            "sfsturbo:shares:updateShareSecurityGroup", "sfsturbo:shares:getTag",
            "sfsturbo:shares:getAllTag", "sfsturbo:shares:renameShare",
            "sfsturbo:shares:showClientIpInfo", "sfsturbo:shares:createDataRepositoryTask",
            "sfsturbo:shares:deleteDataRepositoryTask", "sfsturbo:shares:getDataRepositoryTask",
            "sfsturbo:shares:getAllDataRepositoryTasks", "sfsturbo:shares:createFsDir",
            "sfsturbo:shares:showFsDir", "sfsturbo:shares:deleteFsDir",
            "sfsturbo:shares:createFsDirQuota", "sfsturbo:shares:showFsDirQuota",
            "sfsturbo:shares:deleteFsDirQuota", "sfsturbo:shares:updateFsDirQuota",
            "sfsturbo:shares:batchCreateFsDirQuotas", "sfsturbo:shares:listFsDirQuotas",
            "sfsturbo:shares:showFsDirUsage", "sfsturbo:shares:createFsAsyncTask",
            "sfsturbo:shares:showFsAsyncTask", "sfsturbo:shares:listFsAsyncTasks",
            "sfsturbo:shares:deleteFsAsyncTask", "sfsturbo:shares:createBackendTarget",
            "sfsturbo:shares:showBackendTargetInfo", "sfsturbo:shares:listBackendTargets",
            "sfsturbo:shares:deleteBackendTarget", "sfsturbo:shares:updateObsTargetPolicy",
            "sfsturbo:shares:updateObsTargetAttributes", "sfsturbo:shares:listPermRules",
            "sfsturbo:shares:showPermRule", "sfsturbo:shares:createPermRule",
            "sfsturbo:shares:updatePermRule", "sfsturbo:shares:deletePermRule",
            "sfsturbo:shares:showLdap", "sfsturbo:shares:createLdap",
            "sfsturbo:shares:updateLdap", "sfsturbo:shares:deleteLdap",
            "sfsturbo:shares:addActiveDirectoryDomain", "sfsturbo:shares:deleteActiveDirectoryDomain",
            "sfsturbo:shares:showActiveDirectoryDomain", "sfsturbo:shares:updateActiveDirectoryDomain",
        ],
    },
    "vpc": {  # iam_11_0017
        "actions": [
            "vpc:vpcs:create", "vpc:vpcs:get", "vpc:vpcs:list", "vpc:vpcs:update",
            "vpc:vpcs:delete", "vpc:subnets:create", "vpc:subnets:get", "vpc:subnets:list",
            "vpc:subnets:update", "vpc:subnets:delete", "vpc:subnets:createReservation",
            "vpc:subnets:getReservation", "vpc:subnets:listReservations",
            "vpc:subnets:updateReservation", "vpc:subnets:deleteReservation",
            "vpc:securityGroups:create", "vpc:securityGroups:get", "vpc:securityGroups:list",
            "vpc:securityGroups:update", "vpc:securityGroups:delete",
            "vpc:securityGroupRules:create", "vpc:securityGroupRules:get",
            "vpc:securityGroupRules:list", "vpc:securityGroupRules:update",
            "vpc:securityGroupRules:delete", "vpc:ports:create", "vpc:ports:get",
            "vpc:ports:list", "vpc:ports:update", "vpc:ports:delete",
            "vpc:routeTables:create", "vpc:routeTables:get", "vpc:routeTables:list",
            "vpc:routeTables:update", "vpc:routeTables:associate", "vpc:routeTables:delete",
            "vpc:addressGroups:create", "vpc:addressGroups:get", "vpc:addressGroups:list",
            "vpc:addressGroups:update", "vpc:addressGroups:delete", "vpc:firewalls:create",
            "vpc:firewalls:get", "vpc:firewalls:list", "vpc:firewalls:update",
            "vpc:firewalls:delete", "vpc:subNetworkInterfaces:create",
            "vpc:subNetworkInterfaces:get", "vpc:subNetworkInterfaces:list",
            "vpc:subNetworkInterfaces:update", "vpc:subNetworkInterfaces:delete",
            "vpc:vpcs:createTags", "vpc:vpcs:deleteTags", "vpc:subnets:createTags",
            "vpc:subnets:deleteTags", "vpc:addressGroups:createTags",
            "vpc:addressGroups:deleteTags", "vpc:securityGroups:createTags",
            "vpc:securityGroups:deleteTags", "vpc:firewalls:createTags",
            "vpc:firewalls:deleteTags", "vpc:subNetworkInterfaces:createTags",
            "vpc:subNetworkInterfaces:deleteTags", "vpc:ports:createTags",
            "vpc:ports:deleteTags",
        ],
    },
    "eip": {  # iam_11_0018 - canonical eip:*, not the vpc:* aliases
        "actions": [
            "eip:publicIps:create", "eip:publicIps:batchCreate", "eip:publicIps:list",
            "eip:publicIps:get", "eip:publicIps:update", "eip:publicIps:delete",
            "eip:publicIps:associateInstance", "eip:publicIps:disassociateInstance",
            "eip:publicIps:attachBandwidth", "eip:publicIps:detachBandwidth",
            "eip:publicIps:enableNat64", "eip:publicIps:disableNat64",
            "eip:publicIps:createTags", "eip:publicIps:deleteTags", "eip:bandwidths:create",
            "eip:bandwidths:list", "eip:bandwidths:get", "eip:bandwidths:update",
            "eip:bandwidths:delete", "eip:bandwidths:insertPublicIps",
            "eip:bandwidths:removePublicIps", "eip:bandwidthRules:create",
            "eip:bandwidthRules:list", "eip:bandwidthRules:get", "eip:bandwidthRules:update",
            "eip:bandwidthRules:delete", "eip:globalEips:create", "eip:globalEips:list",
            "eip:globalEips:get", "eip:globalEips:updateGeip", "eip:globalEips:delete",
            "eip:globalEips:associateInstance", "eip:globalEips:disassociateInstance",
            "eip:globalEips:attachBandwidth", "eip:globalEips:detachBandwidth",
            "eip:globalEips:createTags", "eip:globalEips:deleteTags",
            "eip:internetBandwidths:create", "eip:internetBandwidths:list",
            "eip:internetBandwidths:get", "eip:internetBandwidths:update",
            "eip:internetBandwidths:delete", "eip:internetBandwidths:createTags",
            "eip:internetBandwidths:deleteTags", "eip:geipSegments:create",
            "eip:geipSegments:list", "eip:geipSegments:get", "eip:geipSegments:update",
            "eip:geipSegments:delete", "eip:geipSegments:associateInstance",
            "eip:geipSegments:disassociateInstance", "eip:geipSegments:attachBandwidth",
            "eip:geipSegments:detachBandwidth", "eip:geipSegments:createTags",
            "eip:geipSegments:deleteTags",
        ],
    },
    "nat": {  # iam_11_0022
        "actions": [
            "nat:natGateways:create", "nat:natGateways:list", "nat:natGateways:get",
            "nat:natGateways:update", "nat:natGateways:delete", "nat:natGateways:createTags",
            "nat:natGateways:deleteTags", "nat:natGateways:listTags", "nat:snatRules:create",
            "nat:snatRules:list", "nat:snatRules:get", "nat:snatRules:update",
            "nat:snatRules:delete", "nat:dnatRules:create", "nat:dnatRules:list",
            "nat:dnatRules:get", "nat:dnatRules:update", "nat:dnatRules:delete",
            "nat:privateNatGateways:create", "nat:privateNatGateways:list",
            "nat:privateNatGateways:get", "nat:privateNatGateways:update",
            "nat:privateNatGateways:delete", "nat:privateNatGateways:createTags",
            "nat:privateNatGateways:deleteTags", "nat:privateNatGateways:listTags",
            "nat:privateNatSnatRules:create", "nat:privateNatSnatRules:list",
            "nat:privateNatSnatRules:get", "nat:privateNatSnatRules:update",
            "nat:privateNatSnatRules:delete", "nat:privateNatDnatRules:create",
            "nat:privateNatDnatRules:list", "nat:privateNatDnatRules:get",
            "nat:privateNatDnatRules:update", "nat:privateNatDnatRules:delete",
            "nat:privateNatTransitIps:create", "nat:privateNatTransitIps:list",
            "nat:privateNatTransitIps:get", "nat:privateNatTransitIps:delete",
            "nat:privateNatTransitIps:createTags", "nat:privateNatTransitIps:deleteTags",
            "nat:privateNatTransitIps:listTags",
        ],
    },
    "elb": {  # iam_11_0024
        "actions": [
            "elb:availability-zones:list", "elb:loadbalancers:create", "elb:loadbalancers:list",
            "elb:loadbalancers:show", "elb:loadbalancers:update", "elb:loadbalancers:delete",
            "elb:loadbalancers:export", "elb:listeners:create", "elb:listeners:list",
            "elb:listeners:show", "elb:listeners:update", "elb:listeners:delete",
            "elb:listeners:export", "elb:certificates:create", "elb:certificates:list",
            "elb:healthmonitors:create", "elb:healthmonitors:list", "elb:healthmonitors:show",
            "elb:healthmonitors:update", "elb:healthmonitors:delete", "elb:ipgroups:create",
            "elb:ipgroups:list", "elb:l7policies:create", "elb:l7policies:list",
            "elb:l7policies:show", "elb:l7policies:update", "elb:l7policies:delete",
            "elb:l7rules:create", "elb:l7rules:list", "elb:l7rules:show",
            "elb:l7rules:update", "elb:l7rules:delete", "elb:logtanks:create",
            "elb:logtanks:list", "elb:logtanks:show", "elb:logtanks:update",
            "elb:logtanks:delete", "elb:pools:create", "elb:pools:list", "elb:pools:show",
            "elb:pools:update", "elb:pools:delete", "elb:members:create", "elb:members:list",
            "elb:members:show", "elb:members:update", "elb:members:delete",
            "elb:security-policies:create", "elb:security-policies:list",
        ],
    },
    "dns": {  # api-dns/Permission.html (not in the IAM5 tree)
        "actions": [
            "dns:zone:create", "dns:zone:createBatchPublicZonesByName", "dns:zone:list",
            "dns:zone:get", "dns:zone:update", "dns:zone:delete", "dns:zone:associaterouter",
            "dns:zone:disassociaterouter", "dns:zone:setProxyPattern", "dns:zone:transfer",
            "dns:zone:setStatus", "dns:zone:getExport", "dns:zone:enableDnssecConfig",
            "dns:zone:disableDnssecConfig", "dns:zone:getDnssecConfig",
            "dns:zone:getDomainDetection", "dns:recordset:create", "dns:recordset:list",
            "dns:recordset:get", "dns:recordset:update", "dns:recordset:delete",
            "dns:recordset:setStatus", "dns:recordset:associatehealthcheck",
            "dns:recordset:disassociatehealthcheck", "dns:recordset:createPrivateRecordSetImport",
            "dns:recordset:getPrivateRecordSetImport", "dns:recordset:deletePrivateRecordSetImportTask",
            "dns:recordset:createPublicRecordSetImport", "dns:recordset:getPublicRecordSetImport",
            "dns:recordset:deletePublicRecordSetImportTask", "dns:ptr:create", "dns:ptr:list",
            "dns:ptr:get", "dns:ptr:update", "dns:ptr:delete",
        ],
    },
    "rds": {  # iam_11_0033
        "actions": [
            "rds:auditlog:download", "rds:auditlog:list", "rds:auditlog:operate",
            "rds:binlog:get", "rds:binlog:setPolicy", "rds:database:createDatabase",
            "rds:database:drop", "rds:database:list", "rds:database:update",
            "rds:databasePrivilege:grant", "rds:databasePrivilege:revoke",
            "rds:databaseUser:create", "rds:databaseUser:drop", "rds:databaseUser:list",
            "rds:databaseUser:update", "rds:instance:SetMsdtcHosts",
            "rds:instance:buildDrRelation", "rds:instance:createTag",
            "rds:instance:deleteDisasterRecovery", "rds:instance:deleteInstance",
            "rds:instance:deleteTag", "rds:instance:enableSecondLevelMonitoring",
            "rds:instance:extendSpace", "rds:instance:get", "rds:instance:getAutoEnlargePolicy",
            "rds:instance:getBackupPolicy", "rds:instance:getDBProxy", "rds:instance:getDnsName",
            "rds:instance:getMsdtcHosts", "rds:instance:getParameter",
            "rds:instance:getProxyFlavors", "rds:instance:getReplicaStatus",
            "rds:instance:getRestoreTime", "rds:instance:getSecondLevelMonitoringConfig",
            "rds:instance:modifyBackupPolicy", "rds:instance:modifyIp", "rds:instance:modifyPort",
            "rds:instance:modifyProxy", "rds:instance:modifyStrategy",
            "rds:instance:modifySynchronizeModel", "rds:instance:openReadonly",
            "rds:instance:queryRecoveryTimeWindow", "rds:instance:restart",
            "rds:instance:setAutoEnlargePolicy", "rds:instance:showReplayDelayStatus",
            "rds:instance:singleToHa", "rds:instance:start", "rds:instance:stop",
            "rds:instance:switchLogReplay", "rds:instance:switchover", "rds:instance:tde",
            "rds:instance:updateDnsName", "rds:instance:updateName",
            "rds:instance:updateOpsWindow", "rds:instance:updateParameter",
            "rds:instance:updateRemark", "rds:instance:upgradeDatabaseVersion",
            "rds:log:download", "rds:log:getErrorLogs", "rds:log:getSlowLogs",
            "rds:log:setSlowLogSensitiveStatus", "rds:password:update",
        ],
    },
    "kms": {  # iam_11_1011
        "actions": [
            "kms:alias:associate", "kms:alias:create", "kms:alias:delete",
            "kms:cmk:cancelKeyDeletion", "kms:cmk:create", "kms:cmk:createDataKey",
            "kms:cmk:createDataKeyWithoutPlaintext", "kms:cmk:createGrant",
            "kms:cmk:createTag", "kms:cmk:createTags", "kms:cmk:decryptData",
            "kms:cmk:decryptDataKey", "kms:cmk:deleteMaterial", "kms:cmk:deleteTag",
            "kms:cmk:disable", "kms:cmk:disableRotation", "kms:cmk:enable",
            "kms:cmk:enableRotation", "kms:cmk:encryptData", "kms:cmk:encryptDataKey",
            "kms:cmk:generateMac", "kms:cmk:get", "kms:cmk:getMaterial",
            "kms:cmk:getPublicKey", "kms:cmk:getRotation", "kms:cmk:getTags",
            "kms:cmk:importMaterial", "kms:cmk:list", "kms:cmk:listGrants",
            "kms:cmk:replicate", "kms:cmk:revokeGrant", "kms:cmk:scheduleKeyDeletion",
            "kms:cmk:sign", "kms:cmk:updateKeyAlias", "kms:cmk:updateKeyDescription",
            "kms:cmk:updatePrimaryRegion", "kms:cmk:updateRotation", "kms:cmk:verify",
            "kms:cmk:verifyMac",
        ],
    },
    "csms": {  # iam_11_1013
        "actions": [
            "csms:secret:batchCreateOrDeleteTags", "csms:secret:create",
            "csms:secret:createStage", "csms:secret:createTag", "csms:secret:createVersion",
            "csms:secret:delete", "csms:secret:deleteStage", "csms:secret:deleteTag",
            "csms:secret:get", "csms:secret:getStage", "csms:secret:getVersion",
            "csms:secret:list", "csms:secret:listTags", "csms:secret:listVersion",
            "csms:secret:restoreSecret", "csms:secret:rotate", "csms:secret:scheduleDeletion",
            "csms:secret:update", "csms:secret:updateStage", "csms:secret:updateVersion",
        ],
    },
    "smn": {  # iam_11_0093
        "actions": [
            "smn:topic:create", "smn:topic:updateTopic", "smn:topic:get", "smn:topic:delete",
            "smn:topic:listAttributes", "smn:topic:deleteAttribute", "smn:topic:updateAttribute",
            "smn:topic:subscribe", "smn:topic:listSubscriptionsByTopic",
            "smn:topic:deleteSubscription", "smn:topic:updateSubscription", "smn:topic:publish",
            "smn:tag:create", "smn:tag:delete", "smn:tag:batchModify",
            "smn:topic:createLogTank", "smn:topic:listLogTank", "smn:topic:updateLogTank",
            "smn:topic:deleteLogTank", "smn:topic:createKmsKey", "smn:topic:getKmsKey",
            "smn:topic:updateKmsKey", "smn:topic:deleteKmsKey",
        ],
    },
    "lts": {  # iam_11_0094 - reads are tag-conditioned only; single EP action
        "actions": ["lts:logStream:createLogStream"],
    },
    "aom": {  # iam_11_0111 - NO actions support g:EnterpriseProjectId
        "actions": [],
    },
    "ces": {  # iam_11_0092
        "actions": [
            "ces:alarms:create", "ces:alarms:list", "ces:alarms:put", "ces:alarms:putAction",
            "ces:alarms:get", "ces:alarms:delete", "ces:alarms:getInstanceStatus",
            "ces:alarms:getClassInfo", "ces:alarms:listNamespaces",
            "ces:alarms:listOneClickAlarms", "ces:alarms:putOneClickAlarms",
            "ces:alarms:createOneClickAlarms", "ces:alarms:deleteOneClickAlarms",
            "ces:alarms:putOneClickAlarmPolicies", "ces:alarms:putOneClickAlarmNotifications",
            "ces:alarms:addResources", "ces:alarms:deleteResources", "ces:alarms:getPolicies",
            "ces:alarms:getResources", "ces:alarms:updatePolicies",
            "ces:alarms:putAlarmNotifications", "ces:alarms:putNotificationMaskRules",
            "ces:alarms:listNotificationMaskRules", "ces:alarms:listNotificationMaskResources",
            "ces:alarms:deleteNotificationMaskRules", "ces:dashboards:create",
            "ces:dashboards:get", "ces:dashboards:list", "ces:dashboards:put",
            "ces:dashboards:delete", "ces:alarmHistory:list", "ces:alarmHistory:listNamespaces",
            "ces:alarmHistory:statistics", "ces:customAlarmTemplates:create",
            "ces:customAlarmTemplates:delete", "ces:customAlarmTemplates:get",
            "ces:customAlarmTemplates:list", "ces:customAlarmTemplates:listAssociatedAlarms",
            "ces:customAlarmTemplates:put", "ces:customAlarmTemplates:associateResourceGroup",
            "ces:customAlarmTemplates:disassociateResourceGroup", "ces:alarmsContacts:list",
            "ces:alarmsContacts:get", "ces:notificationGroup:create",
            "ces:notificationObject:list", "ces:notificationObject:create",
            "ces:notificationObject:delete", "ces:resourceGroups:addResources",
            "ces:resourceGroups:create", "ces:resourceGroups:delete",
            "ces:resourceGroups:deleteResources", "ces:resourceGroups:get",
            "ces:resourceGroups:getServiceResources", "ces:resourceGroups:list",
            "ces:resourceGroups:put", "ces:resourceGroups:putAssociationAlarmTemplate",
            "ces:resourceGroups:listServices", "ces:siteMonitorRule:list",
            "ces:siteMonitorRule:delete", "ces:siteMonitorRule:create",
            "ces:siteMonitorRule:put", "ces:siteMonitorRule:get",
        ],
    },
}

_all = {a for d in EP_ACTIONS.values() for a in d["actions"]}
_bad = ESSENTIAL_ACTIONS - _all
assert not _bad, f"ESSENTIAL_ACTIONS not in EP_ACTIONS: {sorted(_bad)}"
