"""Artifact copy/rewrite helpers for the customer handover export.

Not a script any more - `py -m lz_pipeline.export_v2 --compat` drives the
export and imports this module for copy_tree, the exclusion sets, and the
generated-file renames/prose rewrites.

What copy_tree does:
  modules-v2/*            -> <target>/modules/*        (paths rewritten)
  envs-acme/*          -> <target>/envs/*           (paths rewritten)
  *.generated.tf          -> renamed to plain .tf names (in the artifact these
                             are ordinary hand-maintained Terraform)
  excluded                -> secrets, *.bak, .terraform, plan/backup litter,
                             python scripts, Excel files

The 00-bootstrap local terraform.tfstate IS shipped: operators cannot manage
the state bucket without it.
"""

import shutil
from pathlib import Path

HERE = Path(__file__).parent
REPO = HERE.parent.parent                   # pipeline/lz_spec -> repo root
MODULES = REPO / "terraform" / "modules"

# generated fan-outs become ordinary files in the artifact; names that would
# collide with existing static files get an -accounts suffix
GENERATED_RENAMES = {
    "providers.generated.tf":     "providers-accounts.tf",
    "outputs.generated.tf":       "outputs-accounts.tf",
    "spokes.generated.tf":        "spokes.tf",
    "tagging.generated.tf":       "tagging.tf",
    "config.generated.tf":        "config.tf",
    "iam-baseline.generated.tf":  "iam-baseline.tf",
    "app-permission-sets.generated.tf": "app-permission-sets.tf",
    "cost-centers.generated.tf":  "cost-centers.tf",
    "observability.generated.tf": "observability.tf",
    "logconverge.generated.tf":   "logconverge.tf",
    "vpn.generated.tf":           "vpn.tf",
    "sgacl.generated.tf":         "sgacl.tf",
}

EXCLUDE_NAMES = {"secrets.auto.tfvars.json", "errored.tfstate", "tfplan", ".gitignore"}
EXCLUDE_SUFFIXES = (".bak", ".backup", ".ps1", ".py", ".xlsx", ".txt")  # .txt: stray plan/log captures
EXCLUDE_DIRS = {".terraform", "__pycache__"}

PROSE_REWRITES = [("# The actual module calls + cross-account provider aliases are GENERATED by\n# build_envs.py into cost-centers.generated.tf and providers.generated.tf\n# (one per account named in the CostCenters sheet's Accounts column). This file\n# only wires the foundation remote state those generated aliases depend on.", '# The module calls + cross-account provider aliases live in cost-centers.tf\n# and providers-accounts.tf (one per target account). This file only wires\n# the foundation remote state those aliases depend on.'), ('# Generated by build_envs.py from the M1 account list into:\n#   providers.generated.tf    (one alias per account)\n#   iam-baseline.generated.tf (master + one module call per account)\n# Add/remove accounts in the 01_Foundation sheet, then re-run build_envs.', '# Per-account fan-out files:\n#   providers-accounts.tf (one alias per account)\n#   iam-baseline.tf       (master + one module call per account)\n# To add or remove an account, copy or delete the matching blocks\n# (see cookbooks/add-account.md).'), ('# Spoke providers + per-VPC module calls are GENERATED (spokes.generated.tf /\n# providers.generated.tf) from the SpokeVPCs table by build_envs.py.', '# Spoke providers + per-VPC module calls live in spokes.tf and\n# providers-accounts.tf (one pair per spoke VPC).'), ('# The central audit module (CTS-admin account) and the per-account ops modules are\n# generated by build_envs.py into providers.generated.tf + observability.generated.tf\n# (one audit call + one ops call per OpsSettings.accounts entry). Do not add module\n# calls here.', '# The central audit module (CTS-admin account) and the per-account ops modules\n# live in providers-accounts.tf + observability.tf (one audit call + one ops\n# call per account). Add or remove module calls there, not here.'), ('# Per-account assume_role providers (audit_admin + ops accounts) are generated by\n# build_envs.py into providers.generated.tf.', '# Per-account assume_role providers (audit_admin + ops accounts) live in\n# providers-accounts.tf.'), ('# envs-v2/03-identity', '# 03-identity'), ('# Wraps modules-v2/organization (relative path).', '# Wraps the organization module (relative path).'), ('modules-v2/perimeter/variables.tf', 'modules/perimeter/variables.tf')]

# source-tree module path -> artifact-relative path
PATH_REWRITE = ("../../../huaweicloud-agentic-tools/modules-v2/", "../../modules/")


def excluded(p: Path) -> bool:
    if p.name in EXCLUDE_NAMES:
        return True
    if any(p.name.endswith(s) for s in EXCLUDE_SUFFIXES):
        return True
    # env-local state stays out EXCEPT the bootstrap state (local backend);
    # state-*.json covers the runbooks' `terraform state pull > state-...json`
    # backup convention in every spelling.
    if p.name.startswith("terraform.tfstate") and p.parent.name != "00-bootstrap":
        return True
    if p.name.startswith("state-") and p.name.endswith(".json"):
        return True
    if p.name.endswith(".pre-rename.backup"):
        return True
    return False


def copy_tree(src: Path, dst: Path, rewrite: bool):
    n = 0
    for p in sorted(src.rglob("*")):
        if p.is_dir() or any(d in p.parts for d in EXCLUDE_DIRS) or excluded(p):
            continue
        rel = p.relative_to(src)
        name = GENERATED_RENAMES.get(rel.name, rel.name)
        out = dst / rel.parent / name
        out.parent.mkdir(parents=True, exist_ok=True)
        if rewrite and p.suffix in (".tf", ".md"):
            text = p.read_text(encoding="utf-8")
            text = text.replace(*PATH_REWRITE)
            for old_txt, new_txt in PROSE_REWRITES:
                text = text.replace(old_txt, new_txt)
            # generated filenames mentioned in comments -> artifact names
            for gname, plain in GENERATED_RENAMES.items():
                text = text.replace(gname, plain)
            if rel.name in GENERATED_RENAMES:
                text = text.replace(
                    "# GENERATED by build_envs.py - do not edit.",
                    "# Per-account fan-out. Ordinary Terraform: edit by hand (copy an existing\n"
                    "# block to add an account; delete a block to remove one).",
                )
            out.write_text(text, encoding="utf-8")
        else:
            shutil.copy2(p, out)
        n += 1
    return n
