# Cost-center enterprise projects, fanned out per target account.
#
# The actual module calls + cross-account provider aliases are GENERATED by
# build_envs.py into cost-centers.generated.tf and providers.generated.tf
# (one per account named in the CostCenters sheet's Accounts column). This file
# only wires the foundation remote state those generated aliases depend on.

data "terraform_remote_state" "foundation" {
  backend = "s3"
  config = {
    bucket                      = var.foundation_state_bucket
    key                         = var.foundation_state_key
    region                      = var.home_region
    endpoints                   = { s3 = "https://obs.${var.home_region}.myhuaweicloud.com" }
    access_key                  = var.master_access_key
    secret_key                  = var.master_secret_key
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    skip_region_validation      = true
    skip_credentials_validation = true
    skip_metadata_api_check     = true
  }
}

locals {
  foundation = data.terraform_remote_state.foundation.outputs
}
