# GENERATED by build_envs.py - do not edit.
# Config (RMS) - central setup in EXAMPLE-Security + per-member recorder fan-out,
# all writing back to the central EXAMPLE-Security OBS bucket (assume_role providers).

provider "huaweicloud" {
  alias        = "config_admin"
  region       = var.home_region
  access_key   = var.master_access_key
  secret_key   = var.master_secret_key
  default_tags = var.default_tags # mandatory tags so the require_mandatory_tags SCP allows creates

  assume_role {
    agency_name = local.foundation.cross_account_agency_name
    domain_name = "EXAMPLE-Security"
  }
}

# Central: recorder + bucket (+ cross-account policy) + agency + aggregator + packs.
module "config_setup" {
  source    = "../../modules/perimeter"
  providers = { huaweicloud = huaweicloud.config_admin }

  enable_scps            = false
  enable_predefined_tags = false
  enable_config          = true
  home_region            = var.home_region
  org_id                 = local.foundation.organization_id
  config                 = merge(var.config, {
    recorder_bucket_writer_domains = [for k, v in local.foundation.accounts : v.id]
  })
  conformance_packs      = [] # packs handled by config_packs below (after all recorders)
}

# Member recorder - EXAMPLE-LogArchive (writes back to the central EXAMPLE-Security bucket).
provider "huaweicloud" {
  alias        = "config_rec_EXAMPLE_LogArchive"
  region       = var.home_region
  access_key   = var.master_access_key
  secret_key   = var.master_secret_key
  default_tags = var.default_tags # mandatory tags so the require_mandatory_tags SCP allows creates

  assume_role {
    agency_name = local.foundation.cross_account_agency_name
    domain_name = "EXAMPLE-LogArchive"
  }
}

module "config_recorder_acct_EXAMPLE_LogArchive" {
  source    = "../../modules/perimeter"
  providers = { huaweicloud = huaweicloud.config_rec_EXAMPLE_LogArchive }

  enable_scps            = false
  enable_predefined_tags = false
  enable_config          = true
  home_region            = var.home_region
  config                 = merge(var.config, { create_recorder_bucket = false, enable_aggregator = false })
  conformance_packs      = []

  depends_on = [module.config_setup] # central bucket + cross-account policy must exist first
}

# Member recorder - EXAMPLE-SharedInfra (writes back to the central EXAMPLE-Security bucket).
provider "huaweicloud" {
  alias        = "config_rec_EXAMPLE_SharedInfra"
  region       = var.home_region
  access_key   = var.master_access_key
  secret_key   = var.master_secret_key
  default_tags = var.default_tags # mandatory tags so the require_mandatory_tags SCP allows creates

  assume_role {
    agency_name = local.foundation.cross_account_agency_name
    domain_name = "EXAMPLE-SharedInfra"
  }
}

module "config_recorder_acct_EXAMPLE_SharedInfra" {
  source    = "../../modules/perimeter"
  providers = { huaweicloud = huaweicloud.config_rec_EXAMPLE_SharedInfra }

  enable_scps            = false
  enable_predefined_tags = false
  enable_config          = true
  home_region            = var.home_region
  config                 = merge(var.config, { create_recorder_bucket = false, enable_aggregator = false })
  conformance_packs      = []

  depends_on = [module.config_setup] # central bucket + cross-account policy must exist first
}

# Member recorder - EXAMPLE-Prod-A (writes back to the central EXAMPLE-Security bucket).
provider "huaweicloud" {
  alias        = "config_rec_EXAMPLE_Prod_A"
  region       = var.home_region
  access_key   = var.master_access_key
  secret_key   = var.master_secret_key
  default_tags = var.default_tags # mandatory tags so the require_mandatory_tags SCP allows creates

  assume_role {
    agency_name = local.foundation.cross_account_agency_name
    domain_name = "EXAMPLE-Prod-A"
  }
}

module "config_recorder_acct_EXAMPLE_Prod_A" {
  source    = "../../modules/perimeter"
  providers = { huaweicloud = huaweicloud.config_rec_EXAMPLE_Prod_A }

  enable_scps            = false
  enable_predefined_tags = false
  enable_config          = true
  home_region            = var.home_region
  config                 = merge(var.config, { create_recorder_bucket = false, enable_aggregator = false })
  conformance_packs      = []

  depends_on = [module.config_setup] # central bucket + cross-account policy must exist first
}

# Member recorder - EXAMPLE-Sandbox1 (writes back to the central EXAMPLE-Security bucket).
provider "huaweicloud" {
  alias        = "config_rec_EXAMPLE_Sandbox1"
  region       = var.home_region
  access_key   = var.master_access_key
  secret_key   = var.master_secret_key
  default_tags = var.default_tags # mandatory tags so the require_mandatory_tags SCP allows creates

  assume_role {
    agency_name = local.foundation.cross_account_agency_name
    domain_name = "EXAMPLE-Sandbox1"
  }
}

module "config_recorder_acct_EXAMPLE_Sandbox1" {
  source    = "../../modules/perimeter"
  providers = { huaweicloud = huaweicloud.config_rec_EXAMPLE_Sandbox1 }

  enable_scps            = false
  enable_predefined_tags = false
  enable_config          = true
  home_region            = var.home_region
  config                 = merge(var.config, { create_recorder_bucket = false, enable_aggregator = false })
  conformance_packs      = []

  depends_on = [module.config_setup] # central bucket + cross-account policy must exist first
}

# Org conformance packs - created after ALL recorders exist (central + members).
module "config_packs" {
  source    = "../../modules/perimeter"
  providers = { huaweicloud = huaweicloud.config_admin }

  enable_scps            = false
  enable_predefined_tags = false
  enable_config          = true
  home_region            = var.home_region
  org_id                 = local.foundation.organization_id
  config                 = merge(var.config, { enable_recorder = false, create_recorder_bucket = false, create_recorder_agency = false, enable_aggregator = false })
  # excluded_accounts resolution: a 32-hex token is used as a domain ID as-is;
  # any other token is treated as an M1 account name and resolved to its domain
  # ID. The management (master) account is ALWAYS excluded - it has no recorder
  # (not in the fan-out), so the org pack would CREATE_FAILED trying to deploy there.
  conformance_packs = [for p in var.conformance_packs : merge(p, {
    excluded_accounts = concat(
      [for a in try(p.excluded_accounts, []) : can(regex("^[0-9a-f]{32}$", a)) ? a : local.foundation.accounts[a].id],
      [local.foundation.master_account_id],
    )
  })]

  depends_on = [module.config_setup, module.config_recorder_acct_EXAMPLE_LogArchive, module.config_recorder_acct_EXAMPLE_SharedInfra, module.config_recorder_acct_EXAMPLE_Prod_A, module.config_recorder_acct_EXAMPLE_Sandbox1]
}
