# GENERATED by build_envs.py - do not edit.
# Predefined-tag dictionary applied to the master account + every M1 account.

module "predef_tags_master" {
  source = "../../modules/perimeter"

  enable_scps            = false
  enable_predefined_tags = true
  predefined_tags        = var.predefined_tags
}

module "predef_tags_acct_EXAMPLE_LogArchive" {
  source    = "../../modules/perimeter"
  providers = { huaweicloud = huaweicloud.acct_EXAMPLE_LogArchive }

  enable_scps            = false
  enable_predefined_tags = true
  predefined_tags        = var.predefined_tags
}

module "predef_tags_acct_EXAMPLE_Security" {
  source    = "../../modules/perimeter"
  providers = { huaweicloud = huaweicloud.acct_EXAMPLE_Security }

  enable_scps            = false
  enable_predefined_tags = true
  predefined_tags        = var.predefined_tags
}

module "predef_tags_acct_EXAMPLE_SharedInfra" {
  source    = "../../modules/perimeter"
  providers = { huaweicloud = huaweicloud.acct_EXAMPLE_SharedInfra }

  enable_scps            = false
  enable_predefined_tags = true
  predefined_tags        = var.predefined_tags
}

module "predef_tags_acct_EXAMPLE_Prod_A" {
  source    = "../../modules/perimeter"
  providers = { huaweicloud = huaweicloud.acct_EXAMPLE_Prod_A }

  enable_scps            = false
  enable_predefined_tags = true
  predefined_tags        = var.predefined_tags
}

module "predef_tags_acct_EXAMPLE_Sandbox1" {
  source    = "../../modules/perimeter"
  providers = { huaweicloud = huaweicloud.acct_EXAMPLE_Sandbox1 }

  enable_scps            = false
  enable_predefined_tags = true
  predefined_tags        = var.predefined_tags
}
