"""02-finance: per-account enterprise-project fan-out."""

from pathlib import Path
from ..helpers import MODULE_SOURCE_ROOT, _truthy, _scalar, _acct_alias
from ..builders import _multi_ep_enabled, _eps_accounts, _cost_centers_by_account
from ..templating import render_lines
from ..writer import _backup_if_exists
from .common import _assume_role_provider, _provider_alias_block


_FINANCIAL_MODULE_SRC = MODULE_SOURCE_ROOT + "/financial"


def _emit_finance_codegen(env_dir: Path, spec: dict):
    """Generate per-account provider aliases + cost-center module calls.

    One module call per target account, each passing that account's subset of
    cost centers (var.cost_centers_by_account["<account>"]). Master uses the
    default provider; every other account gets an alias.
    """
    by_acct = _cost_centers_by_account(spec)
    accounts = list(by_acct.keys())                       # preserves first-seen order
    non_master = [a for a in accounts if a != "master"]

    prov = [
        "# GENERATED by build_envs.py - do not edit.",
        "# Provider alias per target account (master uses the default provider).",
        "",
    ]
    for a in non_master:
        prov += _provider_alias_block(a)

    calls = [
        "# GENERATED by build_envs.py - do not edit.",
        "# Cost-center enterprise projects, one module call per target account.",
        "",
    ]
    def _mod(a):
        return "cost_centers_master" if a == "master" else f"cost_centers_{_acct_alias(a)}"

    for a in accounts:
        providers_line = "" if a == "master" else \
            f"  providers = {{ huaweicloud = huaweicloud.{_acct_alias(a)} }}\n"
        calls += render_lines("finance_module_call.tf.tmpl",
                              module_name=_mod(a), src=_FINANCIAL_MODULE_SRC,
                              providers_line=providers_line, account=a) + [""]

    outs = [
        "# GENERATED by build_envs.py - do not edit.",
        "# Cost-center EP IDs keyed by target account.",
        "",
        'output "cost_center_ep_ids_by_account" {',
        "  description = \"Map of account -> { cost-center EP name -> EP ID }.\"",
        "  value = {",
    ]
    for a in accounts:
        outs.append(f'    "{a}" = module.{_mod(a)}.cost_center_ep_ids')
    outs += ["  }", "}", ""]

    for fname, lines in (
        ("providers.generated.tf", prov),
        ("cost-centers.generated.tf", calls),
        ("outputs.generated.tf", outs),
    ):
        path = env_dir / fname
        _backup_if_exists(path)
        path.write_text("\n".join(lines), encoding="utf-8")
