"""03-identity: per-account IAM baseline fan-out."""
import re

from pathlib import Path
from ..helpers import MODULE_SOURCE_ROOT, _account_names, _acct_alias
from ..templating import render_lines
from ..writer import _backup_if_exists
from .common import _assume_role_provider, _provider_alias_block


_IDENTITY_MODULE_SRC = MODULE_SOURCE_ROOT + "/identity"


def _emit_identity_codegen(env_dir: Path, spec: dict):
    """Generate per-account IAM-baseline fan-out (env 03-identity).

    IC content runs once in master (static main.tf). The IAM baseline runs in
    EVERY account (master + each M1 account) — Terraform can't for_each
    providers, so one alias + one module call per account is generated here.
    """
    accounts = _account_names(spec)

    prov = [
        "# GENERATED by build_envs.py - do not edit.",
        "# Provider alias per M1 account (master uses the default provider).",
        "",
    ]
    for n in accounts:
        prov += _provider_alias_block(n)

    calls = [
        "# GENERATED by build_envs.py - do not edit.",
        "# IAM baseline applied to the master account + every M1 account.",
        "",
    ]
    calls += render_lines("identity_module_call.tf.tmpl", suffix="master",
                          source_line=f'  source = "{_IDENTITY_MODULE_SRC}"',
                          providers_line="") + [""]
    for n in accounts:
        al = _acct_alias(n)
        calls += render_lines(
            "identity_module_call.tf.tmpl", suffix=al,
            source_line=f'  source    = "{_IDENTITY_MODULE_SRC}"',
            providers_line=f"  providers = {{ huaweicloud = huaweicloud.{al} }}\n",
        ) + [""]

    outs = [
        "# GENERATED by build_envs.py - do not edit.",
        "# Per-account service-agency URNs (consumed by module 6 bucket policies).",
        "",
        'output "agencies_by_account" {',
        "  description = \"Per-account service agencies (name -> URN).\"",
        "  value = {",
        "    master = module.iam_baseline_master.agency_urns",
    ]
    for n in accounts:
        outs.append(f'    "{n}" = module.iam_baseline_{_acct_alias(n)}.agency_urns')
    outs += ["  }", "}", ""]

    for fname, lines in (
        ("providers.generated.tf", prov),
        ("iam-baseline.generated.tf", calls),
        ("outputs.generated.tf", outs),
    ):
        path = env_dir / fname
        _backup_if_exists(path)
        path.write_text("\n".join(lines), encoding="utf-8")

    _emit_app_permission_sets(env_dir, spec)


def _emit_app_permission_sets(env_dir: Path, spec: dict):
    """Application-scoped permission sets (03_Identity.AppPermissionSets).

    Each row's CustomPolicy (a complete v5.0 custom identity policy, EP IDs
    already baked in) is attached verbatim to its permission set. Rows without
    a CustomPolicy get the permission set only. No table rows -> no file (and
    any stale one is removed).
    """
    rows = [r for r in spec.get("03_Identity", {}).get("AppPermissionSets") or []
            if r.get("Name")]
    path = env_dir / "app-permission-sets.generated.tf"
    if not rows:
        _backup_if_exists(path)
        if path.exists():
            path.unlink()
        return

    lines = [
        "# GENERATED by build_envs.py - do not edit.",
        "# Application-scoped permission sets: each row's CustomPolicy from the workbook",
        "# is attached verbatim as the permission set's custom identity policy.",
        "",
    ]
    for r in rows:
        name = r["Name"]
        key = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
        session = r.get("SessionDuration") or "PT8H"
        desc = (r.get("Description") or "").replace("\\", "\\\\").replace('"', '\\"')
        lines += [
            f'resource "huaweicloud_identitycenter_permission_set" "{key}" {{',
            "  instance_id      = local.foundation.identity_center_instance_id",
            f'  name             = "{name}"',
            f'  description      = "{desc}"',
            f'  session_duration = "{session}"',
            "}",
            "",
        ]
        policy = (r.get("CustomPolicy") or "").strip()
        if policy:
            lines += [
                f'resource "huaweicloud_identitycenter_custom_policy_attachment" "{key}" {{',
                "  instance_id       = local.foundation.identity_center_instance_id",
                f"  permission_set_id = huaweicloud_identitycenter_permission_set.{key}.id",
                "  custom_policy     = <<-EOT",
            ]
            lines += ["    " + ln for ln in policy.splitlines()]
            lines += [
                "  EOT",
                "}",
                "",
            ]
    _backup_if_exists(path)
    path.write_text("\n".join(lines), encoding="utf-8")
