"""05-network: spoke module calls + spoke providers + outputs."""

from pathlib import Path
from ..helpers import MODULE_SOURCE_ROOT, _truthy, _scalar, _account_names, _acct_alias
from ..builders import _build_spokes
from ..writer import _backup_if_exists
from .common import _net_alias, _spoke_provider_block


_NETWORK_MODULE_SRC = MODULE_SOURCE_ROOT + "/network"
_VPN_MODULE_SRC = MODULE_SOURCE_ROOT + "/vpn"


def _emit_network_codegen(env_dir: Path, spec: dict):
    """Env 06: dynamic spoke fan-out. One provider per DISTINCT spoke account +
    one module call per SpokeVPCs row (any number per account). The hub module +
    locals stay hand-written in main.tf; spokes reference its er_id / route_table_ids
    directly (one apply)."""
    m3 = spec.get("05_Network", {})
    vpcs = [(v.get("VPCName"), v.get("AccountName"))
            for v in (m3.get("SpokeVPCs") or [])
            if v.get("VPCName") and v.get("AccountName")]
    accounts = []
    for _, acct in vpcs:
        if acct not in accounts:
            accounts.append(acct)

    prov = [
        "# GENERATED by build_envs.py - do not edit.",
        "# One provider per distinct spoke account (default_tags satisfies the",
        "# require_mandatory_tags SCP; per-row Tags override per-key on resources).",
        "",
    ]
    for acct in accounts:
        prov += _spoke_provider_block(f"spoke_{_net_alias(acct)}", acct)

    calls = [
        "# GENERATED by build_envs.py - do not edit.",
        "# One spoke module call per SpokeVPCs row. The hub (module.network_hub) +",
        "# local.vpc_flow_lts are defined in main.tf.",
        "",
    ]
    for vpc_name, acct in vpcs:
        v_al = _net_alias(vpc_name)
        a_al = f"spoke_{_net_alias(acct)}"
        calls += [
            f'module "spoke_{v_al}" {{',
            f'  source    = "{_NETWORK_MODULE_SRC}"',
            # default provider = the spoke account; owner = the hub (ER owner), which
            # performs the cross-account route-table association/propagation.
            "  providers = {",
            f"    huaweicloud       = huaweicloud.{a_al}",
            "    huaweicloud.owner = huaweicloud.hub",
            "  }",
            "",
            "  environment  = var.environment",
            "  enable_spoke = true",
            f'  spoke_vpc_name           = var.spokes["{vpc_name}"].vpc_name',
            f'  spoke_vpc_cidr           = var.spokes["{vpc_name}"].vpc_cidr',
            f'  spoke_vpc_tags           = var.spokes["{vpc_name}"].vpc_tags',
            f'  spoke_subnets            = var.spokes["{vpc_name}"].subnets',
            f'  spoke_er_attachment_name = var.spokes["{vpc_name}"].er_attachment_name',
            f'  spoke_er_attach_subnet   = var.spokes["{vpc_name}"].er_attach_subnet',
            f'  spoke_auto_add_route     = var.spokes["{vpc_name}"].auto_add_route',
            f'  spoke_er_attach_enabled  = var.spokes["{vpc_name}"].er_attach',
            "",
            "  spoke_er_id                 = module.network_hub.er_id",
            "  hub_route_table_ids         = module.network_hub.route_table_ids",
            "  inbound_route_table         = var.inbound_route_table",
            "  outbound_route_table        = var.outbound_route_table",
            "  subnet_dns                  = var.subnet_dns",
            "  enable_vpc_flow_logs        = var.enable_vpc_flow_logs",
            "  flow_log_retention_days     = var.flow_log_retention_days",
            "",
            "  depends_on = [module.network_hub]",
            "}",
            "",
        ]

    outs = [
        "# GENERATED by build_envs.py - do not edit.",
        'output "spoke_vpc_ids" {',
        "  description = \"Spoke VPC IDs keyed by VPC name.\"",
        "  value = {",
    ]
    for vpc_name, _ in vpcs:
        outs.append(f'    "{vpc_name}" = module.spoke_{_net_alias(vpc_name)}.spoke_vpc_id')
    outs += ["  }", "}", ""]

    for fname, lines in (
        ("providers.generated.tf", prov),
        ("spokes.generated.tf", calls),
        ("outputs.generated.tf", outs),
    ):
        path = env_dir / fname
        _backup_if_exists(path)
        path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    # VPN was un-merged into env 10-network-vpn (2026-07); drop a stale copy.
    stale = env_dir / "vpn.generated.tf"
    if stale.exists():
        stale.unlink()


def _emit_vpn_codegen(env_dir: Path, spec: dict):
    """Env 10-network-vpn: the module.vpn call. Standalone since 2026-07 (was
    generated into 05-network): gateways attach to the hub VPC/ER via the
    05-network remote state; vpc_ids mirrors the hub+spoke map. Module name and
    argument VALUES are unchanged from the merged era, so the migrated state
    addresses match exactly."""
    m3 = spec.get("05_Network", {})
    vpcs = [v.get("VPCName") for v in (m3.get("SpokeVPCs") or []) if v.get("VPCName")]

    vpn = [
        "# GENERATED by build_envs.py - do not edit.",
        "# VPN (10_VPN sheet): S2C gateways attach to the 05-network hub VPC/ER,",
        "# resolved via remote state (local.network). Apply 05-network first.",
        "",
        'module "vpn" {',
        f'  source    = "{_VPN_MODULE_SRC}"',
        "  providers = { huaweicloud = huaweicloud.vpn }",
        "",
        "  enterprise_project_id = local.enterprise_project_id",
        "",
        "  vpc_ids = merge(local.network.hub_vpc_ids, {",
    ]
    for vpc_name in vpcs:
        vpn.append(f'    "{vpc_name}" = local.network.spoke_vpc_ids["{vpc_name}"]')
    vpn += [
        "  })",
        "  subnet_ids         = local.network.hub_subnet_ids",
        "  er_id              = local.network.er_id",
        "  er_route_table_ids = local.network.route_table_ids",
        "",
        "  gateways          = var.gateways",
        "  customer_gateways = var.customer_gateways",
        "  connections       = var.connections",
        "}",
        "",
    ]
    path = env_dir / "vpn.generated.tf"
    _backup_if_exists(path)
    path.write_text("\n".join(vpn), encoding="utf-8", newline="\n")
