"""04-perimeter: per-account TMS tags + Config/RMS fan-out."""
import re

import json
from pathlib import Path
from ..helpers import MODULE_SOURCE_ROOT, _truthy, _scalar, _split_csv, _account_names, _acct_alias
from ..writer import _backup_if_exists
from .common import _assume_role_provider, _provider_alias_block


_PERIMETER_MODULE_SRC = MODULE_SOURCE_ROOT + "/perimeter"


def _emit_perimeter_tag_codegen(env_dir: Path, spec: dict):
    accounts = _account_names(spec)

    prov = [
        "# GENERATED by build_envs.py - do not edit.",
        "# Provider alias per M1 account (master uses the default provider in providers.tf).",
        "",
    ]
    for n in accounts:
        prov += _provider_alias_block(n)

    calls = [
        "# GENERATED by build_envs.py - do not edit.",
        "# Predefined-tag dictionary applied to the master account + every M1 account.",
        "",
        'module "predef_tags_master" {',
        f'  source = "{_PERIMETER_MODULE_SRC}"',
        "",
        "  enable_scps            = false",
        "  enable_predefined_tags = true",
        "  predefined_tags        = var.predefined_tags",
        "}",
        "",
    ]
    for n in accounts:
        al = _acct_alias(n)
        calls += [
            f'module "predef_tags_{al}" {{',
            f'  source    = "{_PERIMETER_MODULE_SRC}"',
            f"  providers = {{ huaweicloud = huaweicloud.{al} }}",
            "",
            "  enable_scps            = false",
            "  enable_predefined_tags = true",
            "  predefined_tags        = var.predefined_tags",
            "}",
            "",
        ]

    config_lines = _perimeter_config_codegen(spec)

    for fname, lines in (
        ("providers.generated.tf", prov),
        ("tagging.generated.tf", calls),
        ("config.generated.tf", config_lines),
    ):
        path = env_dir / fname
        _backup_if_exists(path)
        path.write_text("\n".join(lines), encoding="utf-8")


def _perimeter_config_codegen(spec: dict) -> list:
    """Config (RMS) setup module call(s).

    config_admin_account picks where the per-account recorder runs. When that is a
    member account, the call is SPLIT: the recorder/agency/bucket run there (the
    domain-scoped recorder accepts the assumed cross-account token), but the
    ORG-scoped resources (ORGANIZATION aggregator + organization conformance packs)
    must run from the management account (master, default provider) — Huawei's org
    RMS endpoints reject the assumed delegated-admin token (STS 'missing
    request_proof'). When config_admin_account == master, one combined call covers
    everything. Blank account = a comment-only stub (also removes a prior call)."""
    cfg = (spec.get("04_Perimeter", {}) or {}).get("ConfigSetup", {}) or {}
    admin = str(cfg.get("config_admin_account", "") or "").strip()

    head = ["# GENERATED by build_envs.py - do not edit."]
    if not admin:
        return head + [
            "# Config (RMS) setup disabled - ConfigSetup.config_admin_account is blank.",
            "",
        ]

    # All Config resources run in config_admin_account. master uses the default
    # (direct-creds) provider. A member admin account uses a dedicated ASSUME_ROLE
    # provider: unlike the agency_name alias (token-scoping only — OBS would sign
    # with the master AK/SK and the bucket would land in MASTER, and v5 IAM / org
    # RMS reject the agency-scoped master token), assume_role mints TEMPORARY AK/SK
    # + SecurityToken for the member account (STS CreateTemporaryAccessKeyByAgency).
    # OBS then signs as the member (bucket in the member account), and the native
    # member session can satisfy v5 IAM (agency) and org RMS too. Still no
    # per-account secrets — it assumes the agency with the master keys.
    if admin == "master":
        return head + [
            "# Config (RMS) - all resources in the management account (master).",
            "",
            'module "config_setup" {',
            f'  source = "{_PERIMETER_MODULE_SRC}"',
            "",
            "  enable_scps            = false",
            "  enable_predefined_tags = false",
            "  enable_config          = true",
            "  home_region            = var.home_region",
            "  org_id                 = local.foundation.organization_id",
            "  config                 = var.config",
            "  conformance_packs      = var.conformance_packs",
            "}",
            "",
        ]

    # Member admin account. Sec runs the central recorder + bucket + agency +
    # aggregator + conformance packs (assume_role provider). For org conformance
    # packs to deploy org-wide, EVERY member account also needs an enabled recorder;
    # those fan out below, each via its own assume_role provider, and write back to
    # the central Sec bucket (granted by recorder_bucket_writer_domains). All member
    # account domains are granted write on the central bucket.
    members = [n for n in _account_names(spec) if n != admin]
    lines = head + [
        f"# Config (RMS) - central setup in {admin} + per-member recorder fan-out,",
        f"# all writing back to the central {admin} OBS bucket (assume_role providers).",
        "",
    ] + _assume_role_provider("config_admin", admin) + [
        "# Central: recorder + bucket (+ cross-account policy) + agency + aggregator + packs.",
        'module "config_setup" {',
        f'  source    = "{_PERIMETER_MODULE_SRC}"',
        "  providers = { huaweicloud = huaweicloud.config_admin }",
        "",
        "  enable_scps            = false",
        "  enable_predefined_tags = false",
        "  enable_config          = true",
        "  home_region            = var.home_region",
        "  org_id                 = local.foundation.organization_id",
        "  config                 = merge(var.config, {",
        "    recorder_bucket_writer_domains = [for k, v in local.foundation.accounts : v.id]",
        "  })",
        "  conformance_packs      = [] # packs handled by config_packs below (after all recorders)",
        "}",
        "",
    ]
    for n in members:
        al = "config_rec_" + re.sub(r"[^0-9A-Za-z_]", "_", str(n))
        lines += [f"# Member recorder - {n} (writes back to the central {admin} bucket)."]
        lines += _assume_role_provider(al, n)
        lines += [
            f'module "config_recorder_{_acct_alias(n)}" {{',
            f'  source    = "{_PERIMETER_MODULE_SRC}"',
            f"  providers = {{ huaweicloud = huaweicloud.{al} }}",
            "",
            "  enable_scps            = false",
            "  enable_predefined_tags = false",
            "  enable_config          = true",
            "  home_region            = var.home_region",
            "  config                 = merge(var.config, { create_recorder_bucket = false, enable_aggregator = false })",
            "  conformance_packs      = []",
            "",
            "  depends_on = [module.config_setup] # central bucket + cross-account policy must exist first",
            "}",
            "",
        ]
    # Org conformance packs LAST — after the central recorder AND every member
    # recorder exist, so the org-wide deployment doesn't fail on a member without a
    # recorder. Runs in the admin account (config_admin); creates no recorder itself.
    pack_deps = ", ".join(["module.config_setup"] + [f"module.config_recorder_{_acct_alias(n)}" for n in members])
    lines += [
        "# Org conformance packs - created after ALL recorders exist (central + members).",
        'module "config_packs" {',
        f'  source    = "{_PERIMETER_MODULE_SRC}"',
        "  providers = { huaweicloud = huaweicloud.config_admin }",
        "",
        "  enable_scps            = false",
        "  enable_predefined_tags = false",
        "  enable_config          = true",
        "  home_region            = var.home_region",
        "  org_id                 = local.foundation.organization_id",
        "  config                 = merge(var.config, { enable_recorder = false, create_recorder_bucket = false, create_recorder_agency = false, enable_aggregator = false })",
        "  # excluded_accounts resolution: a 32-hex token is used as a domain ID as-is;",
        "  # any other token is treated as an M1 account name and resolved to its domain",
        "  # ID. The management (master) account is ALWAYS excluded - it has no recorder",
        "  # (not in the fan-out), so the org pack would CREATE_FAILED trying to deploy there.",
        "  conformance_packs = [for p in var.conformance_packs : merge(p, {",
        "    excluded_accounts = concat(",
        "      [for a in try(p.excluded_accounts, []) : can(regex(\"^[0-9a-f]{32}$\", a)) ? a : local.foundation.accounts[a].id],",
        "      [local.foundation.master_account_id],",
        "    )",
        "  })]",
        "",
        f"  depends_on = [{pack_deps}]",
        "}",
        "",
    ]
    return lines
