"""11-network-sgacl: per-account workload security-group fan-out."""
from pathlib import Path

from ..helpers import MODULE_SOURCE_ROOT, _acct_alias
from ..writer import _backup_if_exists
from .common import _spoke_provider_block


_SGACL_MODULE_SRC = MODULE_SOURCE_ROOT + "/secgroups"


def _emit_sgacl_codegen(env_dir: Path, spec: dict):
    """One assume_role provider + one secgroups module call per distinct
    SecurityGroups.Account (row order). The account's whole groups/rules slice
    travels as var.secgroups["<account>"]; rules were bucketed to their group's
    account by build_09_sgacl."""
    m = spec.get("11_SGACL", {})
    accounts = []
    for r in m.get("SecurityGroups") or []:
        a = str(r.get("Account") or "").strip()
        if a and a not in accounts:
            accounts.append(a)

    prov = [
        "# GENERATED by build_envs.py - do not edit.",
        "# assume_role providers: one per account owning SecurityGroups rows.",
        "",
    ]
    calls = [
        "# GENERATED by build_envs.py - do not edit.",
        "# Workload security groups (module 15): one call per member account.",
        "",
    ]
    if not accounts:
        calls.append("# No SecurityGroups rows - nothing generated.")
    for a in accounts:
        al = _acct_alias(a)
        prov += _spoke_provider_block(al, a)
        calls += [
            f'module "sgacl_{al}" {{',
            f'  source    = "{_SGACL_MODULE_SRC}"',
            f"  providers = {{ huaweicloud = huaweicloud.{al} }}",
            "",
            f'  security_groups = var.secgroups["{a}"].groups',
            f'  sg_rules        = var.secgroups["{a}"].rules',
            "}",
            "",
            f'output "secgroup_ids_{al}" {{',
            f"  value = module.sgacl_{al}.secgroup_ids",
            "}",
            "",
        ]

    for fname, lines in (
        ("providers.generated.tf", prov),
        ("sgacl.generated.tf", calls),
    ):
        path = env_dir / fname
        _backup_if_exists(path)
        path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
